from core.models.lattice import Lattice
from core.models.space_group import *

class CrystallographicSpaceGroups(object):
    @classmethod
    def get(cls, index):
        return cls.standard_setting[index - 1]

    standard_setting = [
        SpaceGroup(1, 'P 1',
                   Lattice.triclinic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(''),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.NA),
        SpaceGroup(2, 'P -1',
                   Lattice.triclinic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(''),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.NA),
        SpaceGroup(3, 'P 1 2 1',
                   Lattice.monoclinic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.NA),
        SpaceGroup(4, 'P 1 21 1',
                   Lattice.monoclinic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,0.5+y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(5, 'C 1 2 1',
                   Lattice.monoclinic(),
                   Centering.base_centered_C(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(6, 'P 1 m 1',
                   Lattice.monoclinic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(7, 'P 1 c 1',
                   Lattice.monoclinic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(8, 'C 1 m 1',
                   Lattice.monoclinic(),
                   Centering.base_centered_C(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(9, 'C 1 c 1',
                   Lattice.monoclinic(),
                   Centering.base_centered_C(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(10, 'P 1 2 / m 1',
                   Lattice.monoclinic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-x,y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(11, 'P 1 21 / m 1',
                   Lattice.monoclinic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-x,0.5+y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(12, 'C 1 2 / m 1',
                   Lattice.monoclinic(),
                   Centering.base_centered_C(),
                   CentroSymmetric(),
                   Symmetry.get('-x,y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(13, 'P 1 2 / c 1',
                   Lattice.monoclinic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-x,y,0.5-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(14, 'P 1 21 / c 1',
                   Lattice.monoclinic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-x,0.5+y,0.5-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(15, 'C 1 2 / c 1',
                   Lattice.monoclinic(),
                   Centering.base_centered_C(),
                   CentroSymmetric(),
                   Symmetry.get('-x,y,0.5-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(16, 'P 2 2 2',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(17, 'P 2 2 21',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,0.5-z;-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(18, 'P 21 21 2',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;0.5-x,0.5+y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(19, 'P 21 21 2 1',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(20, 'C 2 2 21',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,0.5-z;-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(21, 'C 2 2 2',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(22, 'F 2 2 2',
                   Lattice.orthorhombic(),
                   Centering.face_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(23, 'I 2 2 2',
                   Lattice.orthorhombic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(24, 'I 21 21 2 1',
                   Lattice.orthorhombic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(25, 'P m m 2',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,z;x,-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(26, 'P m c 21',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,z;x,-y,0.5+z;-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(27, 'P c c 2',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,0.5+z;x,-y,0.5+z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(28, 'P m a 2',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-x,y,z;0.5+x,-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(29, 'P c a 21',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-x,y,0.5+z;0.5+x,-y,z;-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(30, 'P n c 2',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,0.5+y,0.5+z;x,0.5-y,0.5+z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(31, 'P m n 21',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,z;0.5+x,-y,0.5+z;0.5-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(32, 'P b a 2',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-x,0.5+y,z;0.5+x,0.5-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(33, 'P n a 21',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-x,0.5+y,0.5+z;0.5+x,0.5-y,z;-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(34, 'P n n 2',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-x,0.5+y,0.5+z;0.5+x,0.5-y,0.5+z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(35, 'C m m 2',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,z;x,-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(36, 'C m c 21',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,z;x,-y,0.5+z;-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(37, 'C c c 2',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,0.5+z;x,-y,0.5+z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(38, 'A m m 2',
                   Lattice.orthorhombic(),
                   Centering.base_centered_A(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,z;x,-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(39, 'A b m 2',
                   Lattice.orthorhombic(),
                   Centering.base_centered_A(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,0.5+y,z;x,0.5-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(40, 'A m a 2',
                   Lattice.orthorhombic(),
                   Centering.base_centered_A(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-x,y,z;0.5+x,-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(41, 'A b a 2',
                   Lattice.orthorhombic(),
                   Centering.base_centered_A(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-x,0.5+y,z;0.5+x,0.5-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(42, 'F m m 2',
                   Lattice.orthorhombic(),
                   Centering.face_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,z;x,-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(43, 'F d d 2',
                   Lattice.orthorhombic(),
                   Centering.face_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.25-x,0.25+y,0.25+z;0.25+x,0.25-y,0.25+z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(44, 'I m m 2',
                   Lattice.orthorhombic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('-x,y,z;x,-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(45, 'I b a 2',
                   Lattice.orthorhombic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-x,0.5+y,z;0.5+x,0.5-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(46, 'I m a 2',
                   Lattice.orthorhombic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-x,y,z;0.5+x,-y,z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(47, 'P m m m',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(48, 'P n n n',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('x,0.5-y,0.5-z;0.5-x,y,0.5-z;0.5-x,0.5-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(49, 'P c c m',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,0.5-z;-x,y,0.5-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(50, 'P b a n',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('x,0.5-y,-z;0.5-x,y,-z;0.5-x,0.5-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(51, 'P m m a',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,-y,-z;-x,y,-z;0.5-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(52, 'P n n a',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('x,0.5-y,0.5-z;0.5-x,0.5+y,0.5-z;0.5-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(53, 'P m n a',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,-z;0.5-x,y,0.5-z;0.5-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(54, 'P c c a',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,-y,0.5-z;-x,y,0.5-z;0.5-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(55, 'P b a m',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;0.5-x,0.5+y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(56, 'P c c n',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,-y,0.5-z;-x,0.5+y,0.5-z;0.5-x,0.5-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(57, 'P b c m',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('x,0.5-y,-z;-x,0.5+y,0.5-z;-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(58, 'P n n m',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,0.5-z;0.5-x,0.5+y,0.5-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(59, 'P m m n',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,-y,-z;-x,0.5+y,-z;0.5-x,0.5-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(60, 'P b c n',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;-x,y,0.5-z;0.5-x,0.5-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(61, 'P b c a',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(62, 'P n m a',
                   Lattice.orthorhombic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,0.5-z;-x,0.5+y,-z;0.5-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(63, 'C m c m',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,0.5-z;-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(64, 'C m c a',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;0.5-x,y,0.5-z;-x,0.5-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(65, 'C m m m',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(66, 'C c c m',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,0.5-z;-x,y,0.5-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(67, 'C m m a',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;0.5-x,y,-z;-x,0.5-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(68, 'C c c a',
                   Lattice.orthorhombic(),
                   Centering.base_centered_C(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,-y,0.5-z;-x,y,0.5-z;0.5-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(69, 'F m m m',
                   Lattice.orthorhombic(),
                   Centering.face_centered(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(70, 'F d d d',
                   Lattice.orthorhombic(),
                   Centering.face_centered(),
                   CentroSymmetric(),
                   Symmetry.get('x,0.25-y,0.25-z;0.25-x,y,0.25-z;0.25-x,0.25-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(71, 'I m m m',
                   Lattice.orthorhombic(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(72, 'I b a m',
                   Lattice.orthorhombic(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;0.5-x,0.5+y,-z;-x,-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(73, 'I b c a',
                   Lattice.orthorhombic(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(74, 'I m m a',
                   Lattice.orthorhombic(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get('0.5+x,0.5-y,0.5-z;0.5-x,y,0.5-z;-x,0.5-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(75, 'P 4',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Y),
        SpaceGroup(76, 'P 41',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,0.25+z;-x,-y,0.5+z;y,-x,0.75+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(77, 'P 42',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,0.5+z;-x,-y,z;y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(78, 'P 43',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,0.75+z;-x,-y,0.5+z;y,-x,0.25+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(79, 'I 4',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(80, 'I 41',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,0.5+x,0.25+z;0.5-x,0.5-y,0.5+z;0.5+y,-x,0.75+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(81, 'P -4',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(82, 'I -4',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(83, 'P 4 / m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(84, 'P 42 / m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,0.5+z;-x,-y,z;y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(85, 'P 4 / n',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5-y,x,z;0.5-x,0.5-y,z;y,0.5-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(86, 'P 42 / n',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,0.5+x,0.5+z;0.5-x,0.5-y,z;0.5+y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(87, 'I 4 / m',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(88, 'I 41 / a',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get('0.75-y,0.25+x,0.25+z;0.5-x,-y,0.5+z;0.75+y,0.75-x,0.75+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(89, 'P 4 2 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;y,x,-z;x,-y,-z;-y,-x,-z;-x,y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(90, 'P 4 21 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('0.5-y,0.5+x,z;-x,-y,z;0.5+y,0.5-x,z;y,x,-z;0.5+x,0.5-y,-z;-y,-x,-z;0.5-x,0.5+y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(91, 'P 41 2 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,0.25+z;-x,-y,0.5+z;y,-x,0.75+z;y,x,0.75-z;x,-y,0.5-z;-y,-x,0.25-z;-x,y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(92, 'P 41 21 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,0.5+x,0.25+z;-x,-y,0.5+z;0.5+y,0.5-x,0.75+z;y,x,-z;0.5+x,0.5-y,0.75-z;-y,-x,0.5-z;0.5-x,0.5+y,0.25-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(93, 'P 42 2 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,0.5+z;-x,-y,z;y,-x,0.5+z;y,x,0.5-z;x,-y,-z;-y,-x,0.5-z;-x,y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(94, 'P 42 21 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,0.5+x,0.5+z;-x,-y,z;0.5+y,0.5-x,0.5+z;y,x,-z;0.5+x,0.5-y,0.5-z;-y,-x,-z;0.5-x,0.5+y,0.5-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(95, 'P 43 2 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,0.75+z;-x,-y,0.5+z;y,-x,0.25+z;y,x,0.25-z;x,-y,0.5-z;-y,-x,0.75-z;-x,y,-z'),
                   AsymmetricUnit.EIGHT_Z,
                   UniqueAxis.Z),
        SpaceGroup(96, 'P 43 21 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,0.5+x,0.75+z;-x,-y,0.5+z;0.5+y,0.5-x,0.25+z;y,x,-z;0.5+x,0.5-y,0.25-z;-y,-x,0.5-z;0.5-x,0.5+y,0.75-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(97, 'I 4 2 2',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;y,x,-z;x,-y,-z;-y,-x,-z;-x,y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(98, 'I 41 2 2',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,0.5+x,0.25+z;0.5-x,0.5-y,0.5+z;0.5+y,-x,0.75+z;y,x,-z;0.5+x,-y,0.75-z;0.5-y,0.5-x,0.5-z;-x,0.5+y,0.25-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(99, 'P 4 m m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;-x,y,z;y,x,z;x,-y,z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(100, 'P 4 b m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;0.5-x,0.5+y,z;0.5+y,0.5+x,z;0.5+x,0.5-y,z;0.5-y,0.5-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(101, 'P 42 c m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,0.5+z;-x,-y,z;y,-x,0.5+z;-x,y,0.5+z;y,x,z;x,-y,0.5+z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(102, 'P 42 n m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,0.5+x,0.5+z;-x,-y,z;0.5+y,0.5-x,0.5+z;0.5-x,0.5+y,0.5+z;y,x,z;0.5+x,0.5-y,0.5+z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(103, 'P 4 c c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;-x,y,0.5+z;y,x,0.5+z;x,-y,0.5+z;-y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(104, 'P 4 n c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x,z;-x,-y,z;y,-x,z;0.5-x,0.5+y,0.5+z;0.5+y,0.5+x,0.5+z;0.5+x,0.5-y,0.5+z;0.5-y,0.5-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(105, 'P 42 m c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,0.5+z;-x,-y,z;y,-x,0.5+z;-x,y,z;y,x,0.5+z;x,-y,z;-y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(106, 'P 42 b c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x,0.5+z;-x,-y,z;y,-x,0.5+z;0.5-x,0.5+y,z;0.5+y,0.5+x,0.5+z;0.5+x,0.5-y,z;0.5-y,0.5-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(107, 'I 4 m m',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;-x,y,z;y,x,z;x,-y,z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(108, 'I 4 c m',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;-x,y,0.5+z;y,x,0.5+z;x,-y,0.5+z;-y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(109, 'I 41 m d',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,0.5+x,0.25+z;0.5-x,0.5-y,0.5+z;0.5+y,-x,0.75+z;-x,y,z;y,0.5+x,0.25+z;0.5+x,0.5-y,0.5+z;0.5-y,-x,0.75+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(110, 'I 41 c d',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,0.5+x,0.25+z;0.5-x,0.5-y,0.5+z;0.5+y,-x,0.75+z;-x,y,0.5+z;y,0.5+x,0.75+z;0.5+x,0.5-y,z;0.5-y,-x,0.25+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(111, 'P -4 2 m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z;x,-y,-z;y,x,z;-x,y,-z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(112, 'P -4 2 c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z;x,-y,0.5-z;y,x,0.5+z;-x,y,0.5-z;-y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(113, 'P -4 21 m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z;0.5+x,0.5-y,-z;0.5+y,0.5+x,z;0.5-x,0.5+y,-z;0.5-y,0.5-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(114, 'P -4 21 c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'y,-x,-z;-x,-y,z;-y,x,-z;0.5+x,0.5-y,0.5-z;0.5+y,0.5+x,0.5+z;0.5-x,0.5+y,0.5-z;0.5-y,0.5-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(115, 'P -4 m 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z;-x,y,z;-y,-x,-z;x,-y,z;y,x,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(116, 'P -4 c 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z;-x,y,0.5+z;-y,-x,0.5-z;x,-y,0.5+z;y,x,0.5-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(117, 'P -4 b 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z;0.5-x,0.5+y,z;0.5-y,0.5-x,-z;0.5+x,0.5-y,z;0.5+y,0.5+x,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(118, 'P -4 n 2',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'y,-x,-z;-x,-y,z;-y,x,-z;0.5-x,0.5+y,0.5+z;0.5-y,0.5-x,0.5-z;0.5+x,0.5-y,0.5+z;0.5+y,0.5+x,0.5-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(119, 'I -4 m 2',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z;-x,y,z;-y,-x,-z;x,-y,z;y,x,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(120, 'I -4 c 2',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z;-x,y,0.5+z;-y,-x,0.5-z;x,-y,0.5+z;y,x,0.5-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(121, 'I -4 2 m',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('y,-x,-z;-x,-y,z;-y,x,-z;x,-y,-z;y,x,z;-x,y,-z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(122, 'I -4 2 d',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'y,-x,-z;-x,-y,z;-y,x,-z;x,0.5-y,0.25-z;y,0.5+x,0.25+z;-x,0.5+y,0.25-z;-y,0.5-x,0.25+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(123, 'P 4 / m m m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;-x,y,z;y,x,z;x,-y,z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(124, 'P 4 / m c c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;-x,y,0.5+z;y,x,0.5+z;x,-y,0.5+z;-y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(125, 'P 4 / n b m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5-y,x,z;0.5-x,0.5-y,z;y,0.5-x,z;-x,0.5+y,z;0.5+y,0.5+x,z;0.5+x,-y,z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(126, 'P 4 / n n c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,x,z;0.5-x,0.5-y,z;y,0.5-x,z;-x,0.5+y,0.5+z;0.5+y,0.5+x,0.5+z;0.5+x,-y,0.5+z;-y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(127, 'P 4 / m b m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;0.5-x,0.5+y,z;0.5+y,0.5+x,z;0.5+x,0.5-y,z;0.5-y,0.5-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(128, 'P 4 / m n c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '-y,x,z;-x,-y,z;y,-x,z;0.5-x,0.5+y,0.5+z;0.5+y,0.5+x,0.5+z;0.5+x,0.5-y,0.5+z;0.5-y,0.5-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(129, 'P 4 / n m m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('0.5-y,x,z;0.5-x,0.5-y,z;y,0.5-x,z;0.5-x,y,z;y,x,z;x,0.5-y,z;0.5-y,0.5-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(130, 'P 4 / n c c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,x,z;0.5-x,0.5-y,z;y,0.5-x,z;0.5-x,y,0.5+z;y,x,0.5+z;x,0.5-y,0.5+z;0.5-y,0.5-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(131, 'P 42 / m m c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,0.5+z;-x,-y,z;y,-x,0.5+z;-x,y,z;y,x,0.5+z;x,-y,z;-y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(132, 'P 42 / m c m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,0.5+z;-x,-y,z;y,-x,0.5+z;-x,y,0.5+z;y,x,z;x,-y,0.5+z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(133, 'P 42 / n b c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,x,0.5+z;0.5-x,0.5-y,z;y,0.5-x,0.5+z;-x,0.5+y,z;0.5+y,0.5+x,0.5+z;0.5+x,-y,z;-y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(134, 'P 42 / n n m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,x,0.5+z;0.5-x,0.5-y,z;y,0.5-x,0.5+z;-x,0.5+y,0.5+z;0.5+y,0.5+x,z;0.5+x,-y,0.5+z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(135, 'P 42 / m b c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '-y,x,0.5+z;-x,-y,z;y,-x,0.5+z;0.5-x,0.5+y,z;0.5+y,0.5+x,0.5+z;0.5+x,0.5-y,z;0.5-y,0.5-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(136, 'P 42 / m n m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,0.5+x,0.5+z;-x,-y,z;0.5+y,0.5-x,0.5+z;0.5-x,0.5+y,0.5+z;y,x,z;0.5+x,0.5-y,0.5+z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(137, 'P 42 / n m c',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,x,0.5+z;0.5-x,0.5-y,z;y,0.5-x,0.5+z;0.5-x,y,z;y,x,0.5+z;x,0.5-y,z;0.5-y,0.5-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(138, 'P 42 / n c m',
                   Lattice.tetragonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5-y,x,0.5+z;0.5-x,0.5-y,z;y,0.5-x,0.5+z;0.5-x,y,0.5+z;y,x,z;x,0.5-y,0.5+z;0.5-y,0.5-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(139, 'I 4 / m m m',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;-x,y,z;y,x,z;x,-y,z;-y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(140, 'I 4 / m c m',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x,z;-x,-y,z;y,-x,z;-x,y,0.5+z;y,x,0.5+z;x,-y,0.5+z;-y,-x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(141, 'I 41 / a m d',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.25-y,0.75+x,0.25+z;0.5-x,-y,0.5+z;0.25+y,0.25-x,0.75+z;-x,y,z;0.75+y,0.75+x,0.25+z;0.5+x,-y,0.5+z;0.75-y,0.25-x,0.75+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(142, 'I 41 / a c d',
                   Lattice.tetragonal(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.25-y,0.75+x,0.25+z;0.5-x,-y,0.5+z;0.25+y,0.25-x,0.75+z;-x,y,0.5+z;0.75+y,0.75+x,0.75+z;0.5+x,-y,z;0.75-y,0.25-x,0.25+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(143, 'H 3',
                   Lattice.hexagonal(),
                   Centering.hexagonal(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(144, 'P 31',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,1.0/3.0+z;-x+y,-x,2.0/3.0+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(145, 'P 32',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,2.0/3.0+z;-x+y,-x,1.0/3.0+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(146, 'R 3',
                   Lattice.trigonal(),
                   Centering.rhombohedral(),
                   NonCentroSymmetric(),
                   Symmetry.get('z,x,y;y,z,x'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(147, 'H -3',
                   Lattice.hexagonal(),
                   Centering.hexagonal(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(148, 'R -3',
                   Lattice.trigonal(),
                   Centering.rhombohedral(),
                   CentroSymmetric(),
                   Symmetry.get('z,x,y;y,z,x'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(149, 'P 3 1 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;-y,-x,-z;-x+y,y,-z;x,x-y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(150, 'P 3 2 1',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;y,x,-z;x-y,-y,-z;-x,-x+y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(151, 'P 31 1 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,1.0/3.0+z;-x+y,-x,2.0/3.0+z;-y,-x,2.0/3.0-z;-x+y,y,1.0/3.0-z;x,x-y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(152, 'P 31 2 1',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,1.0/3.0+z;-x+y,-x,2.0/3.0+z;y,x,-z;x-y,-y,2.0/3.0-z;-x,-x+y,1.0/3.0-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(153, 'P 32 1 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,2.0/3.0+z;-x+y,-x,1.0/3.0+z;-y,-x,1.0/3.0-z;-x+y,y,2.0/3.0-z;x,x-y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(154, 'P 32 2 1',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,2.0/3.0+z;-x+y,-x,1.0/3.0+z;y,x,-z;x-y,-y,1.0/3.0-z;-x,-x+y,2.0/3.0-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(155, 'R 3 2',
                   Lattice.trigonal(),
                   Centering.rhombohedral(),
                   NonCentroSymmetric(),
                   Symmetry.get('z,x,y;y,z,x;-x,-z,-y;-z,-y,-x;-y,-x,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(156, 'P 3 m 1',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;-y,-x,z;-x+y,y,z;x,x-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(157, 'P 3 1 m',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   Inversion.UNKNOWN,
                   Symmetry.get('UNKNOWN'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.UNKNOWN),
        SpaceGroup(158, 'P 3 c 1',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;-y,-x,0.5+z;-x+y,y,0.5+z;x,x-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(159, 'P 3 1 c',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;y,x,0.5+z;x-y,-y,0.5+z;-x,-x+y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(160, 'R 3 m',
                   Lattice.trigonal(),
                   Centering.rhombohedral(),
                   NonCentroSymmetric(),
                   Symmetry.get('z,x,y;y,z,x;x,z,y;z,y,x;y,x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(161, 'R 3 c',
                   Lattice.trigonal(),
                   Centering.rhombohedral(),
                   NonCentroSymmetric(),
                   Symmetry.get(' z,x,y; y,z,x;0.5+x,0.5+z,0.5+y;0.5+z,0.5+y,0.5+x;0.5+y,0.5+x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(162, 'P -3 1 m',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;y,x,z;x-y,-y,z;-x,-x+y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(163, 'P -3 1 c',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;y,x,0.5+z;x-y,-y,0.5+z;-x,-x+y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(164, 'P -3 m 1',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;-y,-x,z;-x+y,y,z;x,x-y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(165, 'P -3 c 1',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;-y,-x,0.5+z;-x+y,y,0.5+z;x,x-y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(166, 'R -3 m',
                   Lattice.trigonal(),
                   Centering.rhombohedral(),
                   CentroSymmetric(),
                   Symmetry.get('z,x,y;y,z,x;x,z,y;z,y,x;y,x,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(167, 'R -3 c',
                   Lattice.trigonal(),
                   Centering.rhombohedral(),
                   CentroSymmetric(),
                   Symmetry.get('z,x,y;y,z,x;0.5+x,0.5+z,0.5+y;0.5+z,0.5+y,0.5+x;0.5+y,0.5+x,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(168, 'P 6',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;-x,-y,z;x-y,x,z;y,-x+y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(169, 'P 61',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,1.0/3.0+z;-x+y,-x,2.0/3.0+z;-x,-y,0.5+z;x-y,x,1.0/6.0+z;y,-x+y,5.0/6.0+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(170, 'P 65',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,2.0/3.0+z;-x+y,-x,1.0/3.0+z;-x,-y,0.5+z;x-y,x,5.0/6.0+z;y,-x+y,1.0/6.0+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(171, 'P 62',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,2.0/3.0+z;-x+y,-x,1.0/3.0+z;-x,-y,z;x-y,x,1.0/3.0+z;y,-x+y,2.0/3.0+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(172, 'P 64',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,1.0/3.0+z;-x+y,-x,2.0/3.0+z;-x,-y,z;x-y,x,2.0/3.0+z;y,-x+y,1.0/3.0+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(173, 'P 63',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;-x,-y,1.0/2.0+z;x-y,x,1.0/2.0+z;y,-x+y,1.0/2.0+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(174, 'P -6',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;x,y,-z;-x+y,-x,-z;-y,x-y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(175, 'P 6 / m',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;-x,-y,z;x-y,x,z;y,-x+y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(176, 'P 63 / m',
                   Lattice.trigonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('-y,x-y,z;-x+y,-x,z;-x,-y,0.5+z;x-y,x,0.5+z;y,-x+y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(177, 'P 6 2 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;-x,-y,z;x-y,x,z;y,-x+y,z;y,x,-z;x-y,-y,-z;-x,-x+y,-z;-y,-x,-z;-x+y,y,-z;x,x-y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(178, 'P 61 2 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,1.0/3.0+z;-x+y,-x,2.0/3.0+z;-x,-y,1.0/2.0+z;x-y,x,1.0/6.0+z;y,-x+y,5.0/6.0+z;y,x,1.0/3.0-z;x-y,-y,-z;-x,-x+y,2.0/3.0-z;-y,-x,5.0/6.0-z;-x+y,y,1.0/2.0-z;x,x-y,1.0/6.0-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(179, 'P 65 2 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,2.0/3.0+z;-x+y,-x,1.0/3.0+z;-x,-y,1.0/2.0+z;x-y,x,5.0/6.0+z;y,-x+y,1.0/6.0+z;y,x,2.0/3.0-z;x-y,-y,-z;-x,-x+y,1.0/3.0-z;-y,-x,1.0/6.0-z;-x+y,y,1.0/2.0-z;x,x-y,5.0/6.0-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(180, 'P 62 2 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,2.0/3.0+z;-x+y,-x,1.0/3.0+z;-x,-y,z;x-y,x,1.0/3.0+z;y,-x+y,2.0/3.0+z;y,x,2.0/3.0-z;x-y,-y,-z;-x,-x+y,1.0/3.0-z;-y,-x,2.0/3.0-z;-x+y,y,-z;x,x-y,1.0/3.0-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(181, 'P 64 2 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,1.0/3.0+z;-x+y,-x,2.0/3.0+z;-x,-y,z;x-y,x,2.0/3.0+z;y,-x+y,1.0/3.0+z;y,x,1.0/3.0-z;x-y,-y,-z;-x,-x+y,2.0/3.0-z;-y,-x,1.0/3.0-z;-x+y,y,-z;x,x-y,2.0/3.0-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(182, 'P 63 2 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;-x,-y,1.0/2.0+z;x-y,x,1.0/2.0+z;y,-x+y,1.0/2.0+z;y,x,-z;x-y,-y,-z;-x,-x+y,-z;-y,-x,1.0/2.0-z;-x+y,y,1.0/2.0-z;x,x-y,1.0/2.0-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(183, 'P 6 m m',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;-x,-y,z;x-y,x,z;y,-x+y,z;-y,-x,z;-x+y,y,z;x,x-y,z;y,x,z;x-y,-y,z;-x,-x+y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(184, 'P 6 c c',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;-x,-y,z;x-y,x,z;y,-x+y,z;-y,-x,0.5+z;-x+y,y,0.5+z;x,x-y,0.5+z;y,x,0.5+z;x-y,-y,0.5+z;-x,-x+y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(185, 'P 63 c m',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;-x,-y,0.5+z;x-y,x,0.5+z;y,-x+y,0.5+z;-y,-x,0.5+z;-x+y,y,0.5+z;x,x-y,0.5+z;y,x,z;x-y,-y,z;-x,-x+y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(186, 'P 63 m c',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;-x,-y,0.5+z;x-y,x,0.5+z;y,-x+y,0.5+z;-y,-x,z;-x+y,y,z;x,x-y,z;y,x,0.5+z;x-y,-y,0.5+z;-x,-x+y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(187, 'P -6 m 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   Inversion.UNKNOWN,
                   Symmetry.get('UNKNOWN'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.UNKNOWN),
        SpaceGroup(188, 'P -6 c 2',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;x,y,0.5-z;-x+y,-x,0.5-z;-y,x-y,0.5-z;-y,-x,0.5+z;-x+y,y,0.5+z;x,x-y,0.5+z;-y,-x,-z;-x+y,y,-z;x,x-y,-z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(189, 'P -6 2 m',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;x,y,-z;-x+y,-x,-z;-y,x-y,-z;y,x,-z;x-y,-y,-z;-x,-x+y,-z;y,x,z;x-y,-y,z;-x,-x+y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(190, 'P -6 2 c',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;x,y,0.5-z;-x+y,-x,0.5-z;-y,x-y,0.5-z;y,x,-z;x-y,-y,-z;-x,-x+y,-z;y,x,0.5+z;x-y,-y,0.5+z;-x,-x+y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(191, 'P 6 / m m m',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   Inversion.UNKNOWN,
                   Symmetry.get('UNKNOWN'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.UNKNOWN),
        SpaceGroup(192, 'P 6 / m c c',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;-x,-y,z;x-y,x,z;y,-x+y,z;-y,-x,0.5+z;-x+y,y,0.5+z;x,x-y,0.5+z;y,x,0.5+z;x-y,-y,0.5+z;-x,-x+y,0.5+z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(193, 'P 63 / m c m',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '-y,x-y,z;-x+y,-x,z;-x,-y,0.5+z;x-y,x,0.5+z;y,-x+y,0.5+z;-y,-x,0.5+z;-x+y,y,0.5+z;x,x-y,0.5+z;y,x,z;x-y,-y,z;-x,-x+y,z'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(194, 'P 63 / m m c',
                   Lattice.hexagonal(),
                   Centering.primitive(),
                   Inversion.UNKNOWN,
                   Symmetry.get('UNKNOWN'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.UNKNOWN),
        SpaceGroup(195, 'P 2 3',
                   Lattice.cubic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(196, 'F 2 3',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(197, 'I 2 3',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(198, 'P 21 3',
                   Lattice.cubic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z;y,z,x;0.5-y,-z,0.5+x;0.5+y,0.5-z,-x;-y,0.5+z,0.5-x;z,x,y;-z,0.5+x,0.5-y;0.5-z,-x,0.5+y;0.5+z,0.5-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(199, 'I 21 3',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z;y,z,x;0.5-y,-z,0.5+x;0.5+y,0.5-z,-x;-y,0.5+z,0.5-x;z,x,y;-z,0.5+x,0.5-y;0.5-z,-x,0.5+y;0.5+z,0.5-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(200, 'P m -3',
                   Lattice.cubic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(201, 'P n -3',
                   Lattice.cubic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,0.5-y,0.5-z;0.5-x,y,0.5-z;0.5-x,0.5-y,z;y,z,x;0.5-y,0.5-z,x;y,0.5-z,0.5-x;0.5-y,z,0.5-x;z,x,y;0.5-z,x,0.5-y;0.5-z,0.5-x,y;z,0.5-x,0.5-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(202, 'F m -3',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(203, 'F d -3',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,0.25-y,0.25-z;0.25-x,y,0.25-z;0.25-x,0.25-y,z;y,z,x;0.25-y,0.25-z,x;y,0.25-z,0.25-x;0.25-y,z,0.25-x;z,x,y;0.25-z,x,0.25-y;0.25-z,0.25-x,y;z,0.25-x,0.25-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(204, 'I m -3',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get('x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(205, 'P a -3',
                   Lattice.cubic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z;y,z,x;0.5-y,-z,0.5+x;0.5+y,0.5-z,-x;-y,0.5+z,0.5-x;z,x,y;-z,0.5+x,0.5-y;0.5-z,-x,0.5+y;0.5+z,0.5-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(206, 'I a -3',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z;y,z,x;0.5-y,-z,0.5+x;0.5+y,0.5-z,-x;-y,0.5+z,0.5-x;z,x,y;-z,0.5+x,0.5-y;0.5-z,-x,0.5+y;0.5+z,0.5-x,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(207, 'P 4 3 2',
                   Lattice.cubic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,-z;-y,x,z;y,-x,z;-y,-x,-z;z,y,-x;-z,-y,-x;-z,y,x;z,-y,x;x,z,-y;x,-z,y;-x,-z,-y;-x,z,y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(208, 'P 42 3 2',
                   Lattice.cubic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;0.5+y,0.5+x,0.5-z;0.5-y,0.5+x,0.5+z;0.5+y,0.5-x,0.5+z;0.5-y,0.5-x,0.5-z;0.5+z,0.5+y,0.5-x;0.5-z,0.5-y,0.5-x;0.5-z,0.5+y,0.5+x;0.5+z,0.5-y,0.5+x;0.5+x,0.5+z,0.5-y;0.5+x,0.5-z,0.5+y;0.5-x,0.5-z,0.5-y;0.5-x,0.5+z,0.5+y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(209, 'F 4 3 2',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,-z;-y,x,z;y,-x,z;-y,-x,-z;z,y,-x;-z,-y,-x;-z,y,x;z,-y,x;x,z,-y;x,-z,y;-x,-z,-y;-x,z,y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(210, 'F 41 3 2',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;0.25+y,0.25+x,0.25-z;0.25-y,0.25+x,0.25+z;0.25+y,0.25-x,0.25+z;0.25-y,0.25-x,0.25-z;0.25+z,0.25+y,0.25-x;0.25-z,0.25-y,0.25-x;0.25-z,0.25+y,0.25+x;0.25+z,0.25-y,0.25+x;0.25+x,0.25+z,0.25-y;0.25+x,0.25-z,0.25+y;0.25-x,0.25-z,0.25-y;0.25-x,0.25+z,0.25+y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(211, 'I 4 3 2',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,-z;-y,x,z;y,-x,z;-y,-x,-z;z,y,-x;-z,-y,-x;-z,y,x;z,-y,x;x,z,-y;x,-z,y;-x,-z,-y;-x,z,y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(212, 'P 43 3 2',
                   Lattice.cubic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z;y,z,x;0.5-y,-z,0.5+x;0.5+y,0.5-z,-x;-y,0.5+z,0.5-x;z,x,y;-z,0.5+x,0.5-y;0.5-z,-x,0.5+y;0.5+z,0.5-x,-y;0.25+y,0.75+x,0.75-z;0.75-y,0.25+x,0.75+z;0.75+y,0.75-x,0.25+z;0.25-y,0.25-x,0.25-z;0.25+z,0.75+y,0.75-x;0.25-z,0.25-y,0.25-x;0.75-z,0.25+y,0.75+x;0.75+z,0.75-y,0.25+x;0.25+x,0.75+z,0.75-y;0.75+x,0.75-z,0.25+y;0.25-x,0.25-z,0.25-y;0.75-x,0.25+z,0.75+y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(213, 'P 41 3 2',
                   Lattice.cubic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z;y,z,x;0.5-y,-z,0.5+x;0.5+y,0.5-z,-x;-y,0.5+z,0.5-x;z,x,y;-z,0.5+x,0.5-y;0.5-z,-x,0.5+y;0.5+z,0.5-x,-y;0.75+y,0.25+x,0.25-z;0.25-y,0.75+x,0.25+z;0.25+y,0.25-x,0.75+z;0.75-y,0.75-x,0.75-z;0.75+z,0.25+y,0.25-x;0.75-z,0.75-y,0.75-x;0.25-z,0.75+y,0.25+x;0.25+z,0.25-y,0.75+x;0.75+x,0.25+z,0.25-y;0.25+x,0.25-z,0.75+y;0.75-x,0.75-z,0.75-y;0.25-x,0.75+z,0.25+y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(214, 'I 41 3 2',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z;y,z,x;0.5-y,-z,0.5+x;0.5+y,0.5-z,-x;-y,0.5+z,0.5-x;z,x,y;-z,0.5+x,0.5-y;0.5-z,-x,0.5+y;0.5+z,0.5-x,-y;0.25+y,0.75+x,0.75-z;0.75-y,0.25+x,0.75+z;0.75+y,0.75-x,0.25+z;0.25-y,0.25-x,0.25-z;0.25+z,0.75+y,0.75-x;0.25-z,0.25-y,0.25-x;0.75-z,0.25+y,0.75+x;0.75+z,0.75-y,0.25+x;0.25+x,0.75+z,0.75-y;0.75+x,0.75-z,0.25+y;0.25-x,0.25-z,0.25-y;0.75-x,0.25+z,0.75+y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(215, 'P -4 3 m',
                   Lattice.cubic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,z;-y,x,-z;y,-x,-z;-y,-x,z;z,y,x;-z,-y,x;-z,y,-x;z,-y,-x;x,z,y;x,-z,-y;-x,-z,y;-x,z,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(216, 'F -4 3 m',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,z;-y,x,-z;y,-x,-z;-y,-x,z;z,y,x;-z,-y,x;-z,y,-x;z,-y,-x;x,z,y;x,-z,-y;-x,-z,y;-x,z,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(217, 'I -4 3 m',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,z;-y,x,-z;y,-x,-z;-y,-x,z;z,y,x;-z,-y,x;-z,y,-x;z,-y,-x;x,z,y;x,-z,-y;-x,-z,y;-x,z,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(218, 'P -4 3 n',
                   Lattice.cubic(),
                   Centering.primitive(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;0.5+y,0.5+x,0.5+z;0.5-y,0.5+x,0.5-z;0.5+y,0.5-x,0.5-z;0.5-y,0.5-x,0.5+z;0.5+z,0.5+y,0.5+x;0.5-z,0.5-y,0.5+x;0.5-z,0.5+y,0.5-x;0.5+z,0.5-y,0.5-x;0.5+x,0.5+z,0.5+y;0.5+x,0.5-z,0.5-y;0.5-x,0.5-z,0.5+y;0.5-x,0.5+z,0.5-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(219, 'F -4 3 c',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,0.5+z;-y,x,0.5-z;y,-x,0.5-z;-y,-x,0.5+z;z,y,0.5+x;-z,-y,0.5+x;-z,y,0.5-x;z,-y,0.5-x;x,z,0.5+y;x,-z,0.5-y;-x,-z,0.5+y;-x,z,0.5-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(220, 'I -4 3 d',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   NonCentroSymmetric(),
                   Symmetry.get(
                       '0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z;y,z,x;0.5-y,-z,0.5+x;0.5+y,0.5-z,-x;-y,0.5+z,0.5-x;z,x,y;-z,0.5+x,0.5-y;0.5-z,-x,0.5+y;0.5+z,0.5-x,-y;0.25+y,0.25+x,0.25+z;0.75-y,0.75+x,0.25-z;0.75+y,0.25-x,0.75-z;0.25-y,0.75-x,0.75+z;0.25+z,0.25+y,0.25+x;0.25-z,0.75-y,0.75+x;0.75-z,0.75+y,0.25-x;0.75+z,0.25-y,0.75-x;0.25+x,0.25+z,0.25+y;0.75+x,0.25-z,0.75-y;0.25-x,0.75-z,0.75+y;0.75-x,0.75+z,0.25-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(221, 'P m -3 m',
                   Lattice.cubic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,z;-y,x,-z;y,-x,-z;-y,-x,z;z,y,x;-z,-y,x;-z,y,-x;z,-y,-x;x,z,y;x,-z,-y;-x,-z,y;-x,z,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(222, 'P n -3 n',
                   Lattice.cubic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,0.5-y,0.5-z;0.5-x,y,0.5-z;0.5-x,0.5-y,z;y,z,x;0.5-y,0.5-z,x;y,0.5-z,0.5-x;0.5-y,z,0.5-x;z,x,y;0.5-z,x,0.5-y;0.5-z,0.5-x,y;z,0.5-x,0.5-y;0.5+y,0.5+x,0.5+z;-y,0.5+x,-z;0.5+y,-x,-z;-y,-x,0.5+z;0.5+z,0.5+y,0.5+x;-z,-y,0.5+x;-z,0.5+y,-x;0.5+z,-y,-x;0.5+x,0.5+z,0.5+y;0.5+x,-z,-y;-x,-z,0.5+y;-x,0.5+z,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(223, 'P m -3 n',
                   Lattice.cubic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;0.5+y,0.5+x,0.5+z;0.5-y,0.5+x,0.5-z;0.5+y,0.5-x,0.5-z;0.5-y,0.5-x,0.5+z;0.5+z,0.5+y,0.5+x;0.5-z,0.5-y,0.5+x;0.5-z,0.5+y,0.5-x;0.5+z,0.5-y,0.5-x;0.5+x,0.5+z,0.5+y;0.5+x,0.5-z,0.5-y;0.5-x,0.5-z,0.5+y;0.5-x,0.5+z,0.5-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(224, 'P n -3 m',
                   Lattice.cubic(),
                   Centering.primitive(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,0.5-y,0.5-z;0.5-x,y,0.5-z;0.5-x,0.5-y,z;y,z,x;0.5-y,0.5-z,x;y,0.5-z,0.5-x;0.5-y,z,0.5-x;z,x,y;0.5-z,x,0.5-y;0.5-z,0.5-x,y;z,0.5-x,0.5-y;y,x,z;0.5-y,x,0.5-z;y,0.5-x,0.5-z;0.5-y,0.5-x,z;z,y,x;0.5-z,0.5-y,x;0.5-z,y,0.5-x;z,0.5-y,0.5-x;x,z,y;x,0.5-z,0.5-y;0.5-x,0.5-z,y;0.5-x,z,0.5-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(225, 'F m -3 m',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,z;-y,x,-z;y,-x,-z;-y,-x,z;z,y,x;-z,-y,x;-z,y,-x;z,-y,-x;x,z,y;x,-z,-y;-x,-z,y;-x,z,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(226, 'F m -3 c',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,0.5+z;-y,x,0.5-z;y,-x,0.5-z;-y,-x,0.5+z;z,y,0.5+x;-z,-y,0.5+x;-z,y,0.5-x;z,-y,0.5-x;x,z,0.5+y;x,-z,0.5-y;-x,-z,0.5+y;-x,z,0.5-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(227, 'F d -3 m',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,0.25-y,0.25-z;0.25-x,y,0.25-z;0.25-x,0.25-y,z;y,z,x;0.25-y,0.25-z,x;y,0.25-z,0.25-x;0.25-y,z,0.25-x;z,x,y;0.25-z,x,0.25-y;0.25-z,0.25-x,y;z,0.25-x,0.25-y;y,x,z;0.25-y,x,0.25-z;y,0.25-x,0.25-z;0.25-y,0.25-x,z;z,y,x;0.25-z,0.25-y,x;0.25-z,y,0.25-x;z,0.25-y,0.25-x;x,z,y;x,0.25-z,0.25-y;0.25-x,0.25-z,y;0.25-x,z,0.25-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(228, 'F d -3 c',
                   Lattice.cubic(),
                   Centering.face_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,0.25-y,0.25-z;0.25-x,y,0.25-z;0.25-x,0.25-y,z;y,z,x;0.25-y,0.25-z,x;y,0.25-z,0.25-x;0.25-y,z,0.25-x;z,x,y;0.25-z,x,0.25-y;0.25-z,0.25-x,y;z,0.25-x,0.25-y;y,x,0.5+z;0.25-y,x,0.75-z;y,0.25-x,0.75-z;0.25-y,0.25-x,0.5+z;z,y,0.5+x;0.25-z,0.25-y,0.5+x;0.25-z,y,0.75-x;z,0.25-y,0.75-x;x,z,0.5+y;x,0.25-z,0.75-y;0.25-x,0.25-z,0.5+y;0.25-x,z,0.75-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(229, 'I m -3 m',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       'x,-y,-z;-x,y,-z;-x,-y,z;y,z,x;-y,-z,x;y,-z,-x;-y,z,-x;z,x,y;-z,x,-y;-z,-x,y;z,-x,-y;y,x,z;-y,x,-z;y,-x,-z;-y,-x,z;z,y,x;-z,-y,x;-z,y,-x;z,-y,-x;x,z,y;x,-z,-y;-x,-z,y;-x,z,-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
        SpaceGroup(230, 'I a -3 d',
                   Lattice.cubic(),
                   Centering.body_centered(),
                   CentroSymmetric(),
                   Symmetry.get(
                       '0.5+x,0.5-y,-z;-x,0.5+y,0.5-z;0.5-x,-y,0.5+z;y,z,x;0.5-y,-z,0.5+x;0.5+y,0.5-z,-x;-y,0.5+z,0.5-x;z,x,y;-z,0.5+x,0.5-y;0.5-z,-x,0.5+y;0.5+z,0.5-x,-y;0.25+y,0.25+x,0.25+z;0.75-y,0.75+x,0.25-z;0.75+y,0.25-x,0.75-z;0.25-y,0.75-x,0.75+z;0.25+z,0.25+y,0.25+x;0.25-z,0.75-y,0.75+x;0.75-z,0.75+y,0.25-x;0.75+z,0.25-y,0.75-x;0.25+x,0.25+z,0.25+y;0.75+x,0.25-z,0.75-y;0.25-x,0.75-z,0.75+y;0.75-x,0.75+z,0.25-y'),
                   AsymmetricUnit.UNKNOWN,
                   UniqueAxis.Z),
    ]
