from collections import namedtuple

e = Exception("Value undefined")

Element = namedtuple('Element', ['symbol', 'atomic_number', 'vdw_radius', 'pp_choice'])

vdw_radii = {"H": 1.09, "He": 1.40, "Li": 1.82, "Be": 2.00, "B": 2.00,
             "C": 1.70, "N": 1.55, "O": 1.52, "F": 1.47, "Ne": 1.54,
             "Na": 2.27, "Mg": 1.73, "Al": 2.00, "Si": 2.10, "P": 1.80,
             "S": 1.80, "Cl": 2.0, "Ar": 1.88, 'K': e, 'Ca': e, 'Sc': e,
             'Ti': e, 'V': e, 'Cr': e, 'Mn': e, 'Fe': e, 'Co': e, 'Ni': e, 'Cu': e, 'Zn': e, 'Ga': e,
             'Ge': e, 'As': e, 'Se': e, 'Br': e, 'Kr': e, 'Rb': e, 'Sr': e, 'Y': e, 'Zr': e, 'Nb': e,
             'Mo': e, 'Tc': e, 'Ru': e, 'Rh': e, 'Pd': e, 'Ag': e, 'Cd': e, 'In': e, 'Sn': e, 'Sb': e,
             'Te': e, 'I': 1.98, 'Xe': 2.16, 'Cs': e, 'Ba': e, 'La': e, 'Ce': e, 'Pr': e, 'Nd': e, 'Pm': e,
             'Sm': e, 'Eu': e, 'Gd': e, 'Tb': e, 'Dy': e, 'Ho': e, 'Er': e, 'Tm': e, 'Yb': e, 'Lu': e,
             'Hf': e, 'Ta': e, 'W': e, 'Re': e, 'Os': e, 'Ir': e, 'Pt': e, 'Au': e, 'Hg': e, 'Tl': e,
             'Pb': e, 'Bi': e, 'Po': e, 'At': e, 'Rn': e, 'Fr': e, 'Ra': e, 'Ac': e, 'Th': e, 'Pa': e,
             'U': e, 'Np': e, 'Pu': e, 'Am': e, 'Cm': e, 'Bk': e, 'Cf': e, 'Es': e, 'Fm': e, 'Md': e,
             'No': e, 'Lr': e, 'Rf': e, 'Db': e, 'Sg': e, 'Bh': e, 'Hs': e, 'Mt': e, 'Ds': e,
             'Rg': e, 'Cn': e, 'Nh': e, 'Fl': e, 'Mc': e, 'Lv': e, 'Ts': e, 'Og': e}

atomic_numbers = {'H': 1, 'He': 2, 'Li': 3, 'Be': 4, 'B': 5, 'C': 6, 'N': 7, 'O': 8, 'F': 9, 'Ne': 10, 'Na': 11,
                  'Mg': 12, 'Al': 13, 'Si': 14, 'P': 15, 'S': 16, 'Cl': 17, 'Ar': 18, 'K': 19, 'Ca': 20, 'Sc': 21,
                  'Ti': 22, 'V': 23, 'Cr': 24, 'Mn': 25, 'Fe': 26, 'Co': 27, 'Ni': 28, 'Cu': 29, 'Zn': 30, 'Ga': 31,
                  'Ge': 32, 'As': 33, 'Se': 34, 'Br': 35, 'Kr': 36, 'Rb': 37, 'Sr': 38, 'Y': 39, 'Zr': 40, 'Nb': 41,
                  'Mo': 42, 'Tc': 43, 'Ru': 44, 'Rh': 45, 'Pd': 46, 'Ag': 47, 'Cd': 48, 'In': 49, 'Sn': 50, 'Sb': 51,
                  'Te': 52, 'I': 53, 'Xe': 54, 'Cs': 55, 'Ba': 56, 'La': 57, 'Ce': 58, 'Pr': 59, 'Nd': 60, 'Pm': 61,
                  'Sm': 62, 'Eu': 63, 'Gd': 64, 'Tb': 65, 'Dy': 66, 'Ho': 67, 'Er': 68, 'Tm': 69, 'Yb': 70, 'Lu': 71,
                  'Hf': 72, 'Ta': 73, 'W': 74, 'Re': 75, 'Os': 76, 'Ir': 77, 'Pt': 78, 'Au': 79, 'Hg': 80, 'Tl': 81,
                  'Pb': 82, 'Bi': 83, 'Po': 84, 'At': 85, 'Rn': 86, 'Fr': 87, 'Ra': 88, 'Ac': 89, 'Th': 90, 'Pa': 91,
                  'U': 92, 'Np': 93, 'Pu': 94, 'Am': 95, 'Cm': 96, 'Bk': 97, 'Cf': 98, 'Es': 99, 'Fm': 100, 'Md': 101,
                  'No': 102, 'Lr': 103, 'Rf': 104, 'Db': 105, 'Sg': 106, 'Bh': 107, 'Hs': 108, 'Mt': 109, 'Ds': 110,
                  'Rg': 111, 'Cn': 112, 'Nh': 113, 'Fl': 114, 'Mc': 115, 'Lv': 116, 'Ts': 117, 'Og': 118}

U_corrections = {'Ti': {'d': 5.0}, 'Mn': {'d': 3.0}, 'La': {'f': 9.0}, 'Zr': {'d': 5.79}, 'Co': {'d': 5.0}}

orbital_index = {'d': 2, 'f': 3}

high_spin_states = {'Mn': 4}

"""
Default choices of pseudopotentials for PBE calculations in VASP as recommended by the Materials Project Team.
see https://materialsproject.org/wiki/index.php/Pseudopotentials_Choice for more information
"""
pbe_pp_choices = {'Ru': 'Ru', 'Re': 'Re_pv', 'Rf': None, 'Rg': None, 'Ra': 'Ra_sv', 'Rb': 'Rb_sv', 'Rn': 'Rn',
                  'Rh': 'Rh_pv', 'Be': 'Be_sv', 'Ba': 'Ba_sv', 'Bh': None, 'Bi': 'Bi', 'Bk': None, 'Br': 'Br',
                  'Og': None, 'H': 'H', 'P': 'P', 'Os': 'Os_pv', 'Es': None, 'Ge': 'Ge_d', 'Gd': 'Gd', 'Ga': 'Ga_d',
                  'Pr': 'Pr_3', 'Pt': 'Pt', 'Pu': 'Pu', 'C': 'C', 'Pb': 'Pb_d', 'Pa': 'Pa', 'Pd': 'Pd', 'Xe': 'Xe',
                  'Po': 'Po', 'Pm': 'Pm_3', 'Hs': None, 'Ho': 'Ho_3', 'Hf': 'Hf_pv', 'Hg': 'Hg', 'He': 'He', 'Md': None,
                  'Mg': 'Mg_pv', 'Mc': None, 'K': 'K_sv', 'Mn': 'Mn_pv', 'O': 'O', 'Mt': None, 'S': 'S', 'W': 'W',
                  'Zn': 'Zn', 'Eu': 'Eu', 'Zr': 'Zr_sv', 'Er': 'Er_3', 'Nh': None, 'Ni': 'Ni_pv', 'No': None,
                  'Na': 'Na_pv', 'Nb': 'Nb_pv', 'Nd': 'Nd_3', 'Ne': 'Ne', 'Np': 'Np', 'Fr': 'Fr_sv', 'Fe': 'Fe_pv',
                  'Fl': None, 'Fm': None, 'B': 'B', 'F': 'F', 'Sr': 'Sr_sv', 'N': 'N', 'Kr': 'Kr', 'Si': 'Si',
                  'Sn': 'Sn_d', 'Sm': 'Sm_3', 'V': 'V_sv', 'Sc': 'Sc_sv', 'Sb': 'Sb', 'Sg': None, 'Se': 'Se',
                  'Co': 'Co', 'Cn': None, 'Cm': 'Cm', 'Cl': 'Cl', 'Ca': 'Ca_sv', 'Cf': None, 'Ce': 'Ce', 'Cd': 'Cd',
                  'Tm': 'Tm_3', 'Cs': 'Cs_sv', 'Cr': 'Cr_pv', 'Cu': 'Cu_pv', 'La': 'La', 'Ts': None, 'Li': 'Li_sv',
                  'Lv': None, 'Tl': 'Tl_d', 'Lu': 'Lu_3', 'Lr': None, 'Th': 'Th', 'Ti': 'Ti_pv', 'Te': 'Te',
                  'Tb': 'Tb_3', 'Tc': 'Tc_pv', 'Ta': 'Ta_pv', 'Yb': 'Yb', 'Db': None, 'Dy': 'Dy_3', 'Ds': None,
                  'I': 'I', 'U': 'U', 'Y': 'Y_sv', 'Ac': 'Ac', 'Ag': 'Ag', 'Ir': 'Ir', 'Am': 'Am', 'Al': 'Al',
                  'As': 'As', 'Ar': 'Ar', 'Au': 'Au', 'At': 'At', 'In': 'In_d', 'Mo': 'Mo_pv'}

transition_metals = ['Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh',
                     'Pd', 'Ag', 'Cd', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg']

rare_earth_metals = ['La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Ac',
                     'Th', 'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 'Fm', 'Md', 'No', 'Lr']

element_name_dict = {value: key for key, value in atomic_numbers.items()}

element_dict = {key: Element(symbol=key,
                             atomic_number=atomic_numbers[key],
                             vdw_radius=vdw_radii[key],
                             pp_choice=pbe_pp_choices[key]) for key, v in atomic_numbers.items()}

__max_covalent_by_symbol = {("C", "H"): 1.28
    , ("C", "C"): 1.65
    , ("C", "N"): 1.55
    , ("C", "O"): 1.55
    , ("C", "F"): 1.45
    , ("C", "S"): 1.90
    , ("C", "Cl"): 1.85
    , ("C", "Br"): 1.95
    , ("N", "H"): 1.20
    , ("N", "N"): 1.55
    , ("N", "O"): 1.55
    , ("N", "S"): 1.70
    , ("N", "Hg"): 2.80
    , ("O", "H"): 1.3
    , ("O", "O"): 1.70
    , ("O", "S"): 1.50
    , ("B", "F"): 1.45
    , ("B", "C"): 1.65
    , ("I", "Hg"): 2.80
    , ("Br", "Hg"): 2.50
    , ("S", "S"): 2.5
    , ("H", "H"): 0.85
    , ("C", "I"): 2.2
    , ("S", "Cl"): 1.7
    , ("S", "F"): 1.6
    , ("Cl", "H"): 1.35
    , ("H", "F"): 1.00
    , ("O", "F"): 1.50
    , ("N", "F"): 1.45
    , ("F", "F"): 1.50
                            }
_max_covalent_by_symbol = {}

for k, v in __max_covalent_by_symbol.items():
    _max_covalent_by_symbol[(k[1], k[0])] = v
    _max_covalent_by_symbol[(k[0], k[1])] = v

# Store the ionic radii for elements in different charge states. May not be the most correct value, guide only.
# (Note pymatgen does store ionic radii, but might not have them for every charge state).
ionic_radii = {'Li': {1: 0.76},
               'Na': {1: 1.02},
               'K': {1: 1.38},
               'Rb': {1: 1.52},
               'Cs': {1: 1.67},
               'Mg': {2: 0.721},
               'Ca': {2: 1},
               'Sr': {2: 1.18},
               'Ba': {2: 1.35},
               'F': {-1: 1.33},
               'Cl': {-1: 1.81},
               'Br': {-1: 1.96},
               'I': {-1: 2.2},
               'O': {-2: 1.4},
               'S': {-2: 1.84},
               'Se': {-2: 1.98},
               'Te': {-2: 2.21},
               'Pb': {2: 1.19},
               'Ge': {2: 0.73},
               'Sn': {2: (1.19 + 0.73) / 2},
               'V': {2: 0.79, 5: 0.54},
               'Ta': {2: 0.72, 5: 0.64},
               'Nb': {2: 0.72, 5: 0.64},
               'Ti': {4: 0.605},
               'Zr': {4: 0.72}}

"""
Dictionary of shannon radii from https://github.com/prtkm/ionic-radii
raw data obtained from  http://abulafia.mt.ic.ac.uk/shannon/ptable.php
"""
shannon_radii = {"Ru": {"8": {"IV": {"r_crystal": 0.5, "remark": "", "spin": "", "r_ionic": 0.36}},
                        "3": {"VI": {"r_crystal": 0.82, "remark": "", "spin": "", "r_ionic": 0.68}},
                        "5": {"VI": {"r_crystal": 0.705, "remark": "ER", "spin": "", "r_ionic": 0.565}},
                        "4": {"VI": {"r_crystal": 0.76, "remark": "RM", "spin": "", "r_ionic": 0.62}},
                        "7": {"IV": {"r_crystal": 0.52, "remark": "", "spin": "", "r_ionic": 0.38}},
                        "2": {"VI": {"r_crystal": "", "remark": "", "spin": "", "r_ionic": 0.7}}}, #extrapolated
                 "Re": {"2": {"VI": {"r_crystal": 0.72, "remark": "E", "spin": "", "r_ionic": 0.8}},
                        "5": {"VI": {"r_crystal": 0.72, "remark": "E", "spin": "", "r_ionic": 0.58}},
                        "4": {"VI": {"r_crystal": 0.77, "remark": "RM", "spin": "", "r_ionic": 0.63}},
                        "7": {"VI": {"r_crystal": 0.67, "remark": "", "spin": "", "r_ionic": 0.53},
                              "IV": {"r_crystal": 0.52, "remark": "", "spin": "", "r_ionic": 0.38}},
                        "6": {"VI": {"r_crystal": 0.69, "remark": "E", "spin": "", "r_ionic": 0.55}}},
                 "Ra": {"2": {"XII": {"r_crystal": 1.84, "remark": "R", "spin": "", "r_ionic": 1.7},
                                "VI": {"r_crystal": 1.84, "remark": "R", "spin": "", "r_ionic": 1.6},
                              "VIII": {"r_crystal": 1.62, "remark": "R", "spin": "", "r_ionic": 1.48}}},
                 "Rb": {"1": {"IX": {"r_crystal": 1.77, "remark": "E", "spin": "", "r_ionic": 1.63},
                              "XI": {"r_crystal": 1.83, "remark": "", "spin": "", "r_ionic": 1.69},
                              "VI": {"r_crystal": 1.66, "remark": "", "spin": "", "r_ionic": 1.52},
                              "VII": {"r_crystal": 1.7, "remark": "", "spin": "", "r_ionic": 1.56},
                              "VIII": {"r_crystal": 1.75, "remark": "", "spin": "", "r_ionic": 1.61},
                              "XIV": {"r_crystal": 1.97, "remark": "", "spin": "", "r_ionic": 1.83},
                              "XII": {"r_crystal": 1.86, "remark": "", "spin": "", "r_ionic": 1.72},
                              "X": {"r_crystal": 1.8, "remark": "", "spin": "", "r_ionic": 1.66}}},
                 "Rh": {"2":  {"VI": {"r_crystal": "", "remark": "E", "spin": "", "r_ionic": 0.7}},
                        "3": {"VI": {"r_crystal": 0.805, "remark": "R", "spin": "", "r_ionic": 0.665}},
                        "5": {"VI": {"r_crystal": 0.69, "remark": "", "spin": "", "r_ionic": 0.55}},
                        "4": {"VI": {"r_crystal": 0.74, "remark": "RM", "spin": "", "r_ionic": 0.6}}},
                 "Be": {"2": {"VI": {"r_crystal": 0.59, "remark": "C", "spin": "", "r_ionic": 0.45},
                              "III": {"r_crystal": 0.3, "remark": "", "spin": "", "r_ionic": 0.16},
                              "IV": {"r_crystal": 0.41, "remark": "*", "spin": "", "r_ionic": 0.27}}},
                 "Ba": {"2": {"IX": {"r_crystal": 1.61, "remark": "", "spin": "", "r_ionic": 1.47},
                              "XI": {"r_crystal": 1.71, "remark": "", "spin": "", "r_ionic": 1.57},
                              "VI": {"r_crystal": 1.49, "remark": "", "spin": "", "r_ionic": 1.35},
                              "VII": {"r_crystal": 1.52, "remark": "C", "spin": "", "r_ionic": 1.38},
                              "VIII": {"r_crystal": 1.56, "remark": "", "spin": "", "r_ionic": 1.42},
                              "XII": {"r_crystal": 1.75, "remark": "C", "spin": "", "r_ionic": 1.61},
                              "X": {"r_crystal": 1.66, "remark": "", "spin": "", "r_ionic": 1.52}}},
                 "Bi": {"3": {"VI": {"r_crystal": 1.17, "remark": "R*", "spin": "", "r_ionic": 1.03},
                              "VIII": {"r_crystal": 1.31, "remark": "R", "spin": "", "r_ionic": 1.17},
                              "V": {"r_crystal": 1.1, "remark": "C", "spin": "", "r_ionic": 0.96}},
                        "5": {"VI": {"r_crystal": 0.9, "remark": "E", "spin": "", "r_ionic": 0.76}}},
                 "Bk": {"3": {"VI": {"r_crystal": 1.1, "remark": "R", "spin": "", "r_ionic": 0.96}},
                        "4": {"VI": {"r_crystal": 0.97, "remark": "R", "spin": "", "r_ionic": 0.83},
                              "VIII": {"r_crystal": 1.07, "remark": "R", "spin": "", "r_ionic": 0.93}}},
                 "Br": {"5": {"IIIPY": {"r_crystal": 0.45, "remark": "", "spin": "", "r_ionic": 0.31}},
                        "3": {"IVSQ": {"r_crystal": 0.73, "remark": "", "spin": "", "r_ionic": 0.59}},
                        "-1": {"VI": {"r_crystal": 1.82, "remark": "P", "spin": "", "r_ionic": 1.96}},
                        "7": {"VI": {"r_crystal": 0.53, "remark": "A", "spin": "", "r_ionic": 0.39},
                              "IV": {"r_crystal": 0.39, "remark": "", "spin": "", "r_ionic": 0.25}}},
                 "D": {"1": {"II": {"r_crystal": 0.04, "remark": "", "spin": "", "r_ionic": -0.1}}},
                 "H": {"1": {"I": {"r_crystal": -0.24, "remark": "", "spin": "", "r_ionic": -0.38},
                             "II": {"r_crystal": -0.04, "remark": "", "spin": "", "r_ionic": -0.18}}},
                 "P": {"3": {"VI": {"r_crystal": 0.58, "remark": "A", "spin": "", "r_ionic": 0.44}},
                       "5": {"VI": {"r_crystal": 0.52, "remark": "C", "spin": "", "r_ionic": 0.38},
                             "V": {"r_crystal": 0.43, "remark": "", "spin": "", "r_ionic": 0.29},
                             "IV": {"r_crystal": 0.31, "remark": "*", "spin": "", "r_ionic": 0.17}}},
                 "Os": {"8": {"IV": {"r_crystal": 0.53, "remark": "", "spin": "", "r_ionic": 0.39}},
                        "5": {"VI": {"r_crystal": 0.715, "remark": "E", "spin": "", "r_ionic": 0.575}},
                        "4": {"VI": {"r_crystal": 0.77, "remark": "RM", "spin": "", "r_ionic": 0.63}},
                        "7": {"VI": {"r_crystal": 0.665, "remark": "E", "spin": "", "r_ionic": 0.525}},
                        "6": {"VI": {"r_crystal": 0.685, "remark": "E", "spin": "", "r_ionic": 0.545},
                              "V": {"r_crystal": 0.63, "remark": "", "spin": "", "r_ionic": 0.49}},
                        "2": {"VI": {"r_crystal": "", "remark": "E", "spin": "", "r_ionic": 0.65}}},
                 "OH": {"-1": {"II": {"r_crystal": 1.18, "remark": "", "spin": "", "r_ionic": 1.32},
                               "VI": {"r_crystal": 1.23, "remark": "E", "spin": "", "r_ionic": 1.37},
                               "III": {"r_crystal": 1.2, "remark": "", "spin": "", "r_ionic": 1.34},
                               "IV": {"r_crystal": 1.21, "remark": "E", "spin": "", "r_ionic": 1.35}}},
                 "Ge": {"2": {"VI": {"r_crystal": 0.87, "remark": "A", "spin": "", "r_ionic": 0.73}},
                        "4": {"VI": {"r_crystal": 0.67, "remark": "R*", "spin": "", "r_ionic": 0.53},
                              "IV": {"r_crystal": 0.53, "remark": "*", "spin": "", "r_ionic": 0.39}}},
                 "Gd": {"3": {"VI": {"r_crystal": 1.078, "remark": "R", "spin": "", "r_ionic": 0.938},
                              "VII": {"r_crystal": 1.14, "remark": "", "spin": "", "r_ionic": 1},
                              "VIII": {"r_crystal": 1.193, "remark": "R", "spin": "", "r_ionic": 1.053},
                              "IX": {"r_crystal": 1.247, "remark": "RC", "spin": "", "r_ionic": 1.107}}},
                 "Ga": {"3": {"VI": {"r_crystal": 0.76, "remark": "R*", "spin": "", "r_ionic": 0.62},
                              "V": {"r_crystal": 0.69, "remark": "", "spin": "", "r_ionic": 0.55},
                              "IV": {"r_crystal": 0.61, "remark": "*", "spin": "", "r_ionic": 0.47}},
                        "2": {"VI": {"r_crystal": 0.87, "remark": "A", "spin": "", "r_ionic": 0.71}}, #extrapolate between +1 and +3 states
                        "1": {"VI": {"r_crystal": 0.87, "remark": "A", "spin": "", "r_ionic": 0.81}}},# https://www.webelements.com/gallium/atom_sizes.html
                 "Pr": {"3": {"VI": {"r_crystal": 1.13, "remark": "R", "spin": "", "r_ionic": 0.99},
                              "VIII": {"r_crystal": 1.266, "remark": "R", "spin": "", "r_ionic": 1.126},
                              "IX": {"r_crystal": 1.319, "remark": "R", "spin": "", "r_ionic": 1.179}},
                        "4": {"VI": {"r_crystal": 0.99, "remark": "R", "spin": "", "r_ionic": 0.85},
                              "VIII": {"r_crystal": 1.1, "remark": "R", "spin": "", "r_ionic": 0.96}}},
                 "Pt": {"2": {"IVSQ": {"r_crystal": 0.74, "remark": "", "spin": "", "r_ionic": 0.6},
                              "VI": {"r_crystal": 0.94, "remark": "A", "spin": "", "r_ionic": 0.8}},
                        "5": {"VI": {"r_crystal": 0.71, "remark": "ER", "spin": "", "r_ionic": 0.57}},
                        "4": {"VI": {"r_crystal": 0.765, "remark": "R", "spin": "", "r_ionic": 0.625}}},
                 "Pu": {"3": {"VI": {"r_crystal": 1.14, "remark": "R", "spin": "", "r_ionic": 1}},
                        "5": {"VI": {"r_crystal": 0.88, "remark": "E", "spin": "", "r_ionic": 0.74}},
                        "4": {"VI": {"r_crystal": 1, "remark": "R", "spin": "", "r_ionic": 0.86},
                              "VIII": {"r_crystal": 1.1, "remark": "", "spin": "", "r_ionic": 0.96}},
                        "6": {"VI": {"r_crystal": 0.85, "remark": "R", "spin": "", "r_ionic": 0.71}}},
                 "C": {"4": {"VI": {"r_crystal": 0.3, "remark": "A", "spin": "", "r_ionic": 0.16},
                             "III": {"r_crystal": 0.06, "remark": "", "spin": "", "r_ionic": -0.08},
                             "IV": {"r_crystal": 0.29, "remark": "P", "spin": "", "r_ionic": 0.15}}},
                 "Pb": {"2": {"IX": {"r_crystal": 1.49, "remark": "C", "spin": "", "r_ionic": 1.35},
                              "XI": {"r_crystal": 1.59, "remark": "C", "spin": "", "r_ionic": 1.45},
                              "VI": {"r_crystal": 1.33, "remark": "", "spin": "", "r_ionic": 1.19},
                              "VII": {"r_crystal": 1.37, "remark": "C", "spin": "", "r_ionic": 1.23},
                              "VIII": {"r_crystal": 1.43, "remark": "C", "spin": "", "r_ionic": 1.29},
                              "XII": {"r_crystal": 1.63, "remark": "", "spin": "", "r_ionic": 1.49},
                              "IVPY": {"r_crystal": 1.12, "remark": "C", "spin": "", "r_ionic": 0.98},
                              "X": {"r_crystal": 1.54, "remark": "C", "spin": "", "r_ionic": 1.4}},
                        "4": {"VI": {"r_crystal": 0.915, "remark": "R", "spin": "", "r_ionic": 0.775},
                              "V": {"r_crystal": 0.87, "remark": "E", "spin": "", "r_ionic": 0.73},
                              "VIII": {"r_crystal": 1.08, "remark": "R", "spin": "", "r_ionic": 0.94},
                              "IV": {"r_crystal": 0.79, "remark": "E", "spin": "", "r_ionic": 0.65}}},
                 "Pa": {"3": {"VI": {"r_crystal": 1.18, "remark": "E", "spin": "", "r_ionic": 1.04}},
                        "5": {"VI": {"r_crystal": 0.92, "remark": "", "spin": "", "r_ionic": 0.78},
                              "VIII": {"r_crystal": 1.05, "remark": "", "spin": "", "r_ionic": 0.91},
                              "IX": {"r_crystal": 1.09, "remark": "", "spin": "", "r_ionic": 0.95}},
                        "4": {"VI": {"r_crystal": 1.04, "remark": "R", "spin": "", "r_ionic": 0.9},
                              "VIII": {"r_crystal": 1.15, "remark": "", "spin": "", "r_ionic": 1.01}}},
                 "Pd": {"1": {"II": {"r_crystal": 0.73, "remark": "", "spin": "", "r_ionic": 0.59}},
                        "3": {"VI": {"r_crystal": 0.9, "remark": "", "spin": "", "r_ionic": 0.76}},
                        "2": {"IVSQ": {"r_crystal": 0.78, "remark": "", "spin": "", "r_ionic": 0.64},
                              "VI": {"r_crystal": 1, "remark": "", "spin": "", "r_ionic": 0.86}},
                        "4": {"VI": {"r_crystal": 0.755, "remark": "R", "spin": "", "r_ionic": 0.615}}},
                 "Xe": {"8": {"VI": {"r_crystal": 0.62, "remark": "", "spin": "", "r_ionic": 0.48},
                              "IV": {"r_crystal": 0.54, "remark": "", "spin": "", "r_ionic": 0.4}}},
                 "Po": {"4": {"VI": {"r_crystal": 1.08, "remark": "R", "spin": "", "r_ionic": 0.94},
                              "VIII": {"r_crystal": 1.22, "remark": "R", "spin": "", "r_ionic": 1.08}},
                        "6": {"VI": {"r_crystal": 0.81, "remark": "A", "spin": "", "r_ionic": 0.67}}},
                 "Pm": {"3": {"VI": {"r_crystal": 1.11, "remark": "R", "spin": "", "r_ionic": 0.97},
                              "VIII": {"r_crystal": 1.233, "remark": "R", "spin": "", "r_ionic": 1.093},
                              "IX": {"r_crystal": 1.284, "remark": "R", "spin": "", "r_ionic": 1.144}}},
                 "Ho": {"3": {"VI": {"r_crystal": 1.041, "remark": "R", "spin": "", "r_ionic": 0.901},
                              "VIII": {"r_crystal": 1.155, "remark": "R", "spin": "", "r_ionic": 1.015},
                              "X": {"r_crystal": 1.26, "remark": "", "spin": "", "r_ionic": 1.12},
                              "IX": {"r_crystal": 1.212, "remark": "R", "spin": "", "r_ionic": 1.072}}},
                 "Hf": {"2": {"VI": {"r_crystal": "", "remark": "R", "spin": "", "r_ionic": 0.80}}, #this is just a rough guess
                        "4": {"VI": {"r_crystal": 0.85, "remark": "R", "spin": "", "r_ionic": 0.71},
                              "VII": {"r_crystal": 0.9, "remark": "", "spin": "", "r_ionic": 0.76},
                              "VIII": {"r_crystal": 0.97, "remark": "", "spin": "", "r_ionic": 0.83},
                              "IV": {"r_crystal": 0.72, "remark": "R", "spin": "", "r_ionic": 0.58}}},
                 "Hg": {"1": {"VI": {"r_crystal": 1.33, "remark": "", "spin": "", "r_ionic": 1.19},
                              "III": {"r_crystal": 1.11, "remark": "", "spin": "", "r_ionic": 0.97}},
                        "2": {"II": {"r_crystal": 0.83, "remark": "", "spin": "", "r_ionic": 0.69},
                              "VI": {"r_crystal": 1.16, "remark": "", "spin": "", "r_ionic": 1.02},
                              "VIII": {"r_crystal": 1.28, "remark": "R", "spin": "", "r_ionic": 1.14},
                              "IV": {"r_crystal": 1.1, "remark": "", "spin": "", "r_ionic": 0.96}}},
                 "Mg": {"2": {"VI": {"r_crystal": 0.86, "remark": "*", "spin": "", "r_ionic": 0.72},
                              "V": {"r_crystal": 0.8, "remark": "", "spin": "", "r_ionic": 0.66},
                              "VIII": {"r_crystal": 1.03, "remark": "C", "spin": "", "r_ionic": 0.89},
                              "IV": {"r_crystal": 0.71, "remark": "", "spin": "", "r_ionic": 0.57}}},
                 "K": {"1": {"IX": {"r_crystal": 1.69, "remark": "", "spin": "", "r_ionic": 1.55},
                             "VI": {"r_crystal": 1.52, "remark": "", "spin": "", "r_ionic": 1.38},
                             "VII": {"r_crystal": 1.6, "remark": "", "spin": "", "r_ionic": 1.46},
                             "IV": {"r_crystal": 1.51, "remark": "", "spin": "", "r_ionic": 1.37},
                             "VIII": {"r_crystal": 1.65, "remark": "", "spin": "", "r_ionic": 1.51},
                             "XII": {"r_crystal": 1.78, "remark": "", "spin": "", "r_ionic": 1.64},
                             "X": {"r_crystal": 1.73, "remark": "", "spin": "", "r_ionic": 1.59}}},
                 "Mn": {"3": {"": {"r_crystal": 0.72, "remark": "R", "spin": "Low Spin", "r_ionic": 0.58},
                              "VI": {"r_crystal": 0.785, "remark": "R*", "spin": "High Spin", "r_ionic": 0.645},
                              "V": {"r_crystal": 0.72, "remark": "", "spin": "", "r_ionic": 0.58}},
                        "2": {"": {"r_crystal": 0.97, "remark": "R*", "spin": "High Spin", "r_ionic": 0.83},
                              "VI": {"r_crystal": 0.81, "remark": "E", "spin": "Low Spin", "r_ionic": 0.67},
                              "VII": {"r_crystal": 1.04, "remark": "C", "spin": "High Spin", "r_ionic": 0.9},
                              "IV": {"r_crystal": 0.8, "remark": "", "spin": "High Spin", "r_ionic": 0.66},
                              "VIII": {"r_crystal": 1.1, "remark": "R", "spin": "", "r_ionic": 0.96},
                              "V": {"r_crystal": 0.89, "remark": "C", "spin": "High Spin", "r_ionic": 0.75}},
                        "5": {"IV": {"r_crystal": 0.47, "remark": "R", "spin": "", "r_ionic": 0.33}},
                        "4": {"VI": {"r_crystal": 0.67, "remark": "R*", "spin": "", "r_ionic": 0.53},
                              "IV": {"r_crystal": 0.53, "remark": "R", "spin": "", "r_ionic": 0.39}},
                        "7": {"VI": {"r_crystal": 0.6, "remark": "A", "spin": "", "r_ionic": 0.46},
                              "IV": {"r_crystal": 0.39, "remark": "", "spin": "", "r_ionic": 0.25}},
                        "6": {"IV": {"r_crystal": 0.395, "remark": "", "spin": "", "r_ionic": 0.255}}},
                 "O": {"-2": {"II": {"r_crystal": 1.21, "remark": "", "spin": "", "r_ionic": 1.35},
                              "VI": {"r_crystal": 1.26, "remark": "", "spin": "", "r_ionic": 1.4},
                              "III": {"r_crystal": 1.22, "remark": "", "spin": "", "r_ionic": 1.36},
                              "VIII": {"r_crystal": 1.28, "remark": "", "spin": "", "r_ionic": 1.42},
                              "IV": {"r_crystal": 1.24, "remark": "", "spin": "", "r_ionic": 1.38}}},
                 "S": {"6": {"VI": {"r_crystal": 0.43, "remark": "C", "spin": "", "r_ionic": 0.29},
                             "IV": {"r_crystal": 0.26, "remark": "*", "spin": "", "r_ionic": 0.12}},
                       "4": {"VI": {"r_crystal": 0.51, "remark": "A", "spin": "", "r_ionic": 0.37}},
                       "-2": {"VI": {"r_crystal": 1.7, "remark": "P", "spin": "", "r_ionic": 1.84}}},
                 "W": {"2": {"VI": {"r_crystal": "", "remark": "R*", "spin": "", "r_ionic": 0.68}}, #extrapolate from 4+ and 6+
                        "5": {"VI": {"r_crystal": 0.76, "remark": "R", "spin": "", "r_ionic": 0.62}},
                       "4": {"VI": {"r_crystal": 0.8, "remark": "RM", "spin": "", "r_ionic": 0.66}},
                       "6": {"VI": {"r_crystal": 0.74, "remark": "*", "spin": "", "r_ionic": 0.6},
                             "V": {"r_crystal": 0.65, "remark": "", "spin": "", "r_ionic": 0.51},
                             "IV": {"r_crystal": 0.56, "remark": "*", "spin": "", "r_ionic": 0.42}}},
                 "Zn": {"2": {"VI": {"r_crystal": 0.88, "remark": "R*", "spin": "", "r_ionic": 0.74},
                              "V": {"r_crystal": 0.82, "remark": "*", "spin": "", "r_ionic": 0.68},
                              "VIII": {"r_crystal": 1.04, "remark": "C", "spin": "", "r_ionic": 0.9},
                              "IV": {"r_crystal": 0.74, "remark": "*", "spin": "", "r_ionic": 0.6}}},
                 "Eu": {"3": {"VI": {"r_crystal": 1.087, "remark": "R", "spin": "", "r_ionic": 0.947},
                              "VII": {"r_crystal": 1.15, "remark": "", "spin": "", "r_ionic": 1.01},
                              "VIII": {"r_crystal": 1.206, "remark": "R", "spin": "", "r_ionic": 1.066},
                              "IX": {"r_crystal": 1.26, "remark": "R", "spin": "", "r_ionic": 1.12}},
                        "2": {"VI": {"r_crystal": 1.31, "remark": "", "spin": "", "r_ionic": 1.17},
                              "VII": {"r_crystal": 1.34, "remark": "", "spin": "", "r_ionic": 1.2},
                              "VIII": {"r_crystal": 1.39, "remark": "", "spin": "", "r_ionic": 1.25},
                              "X": {"r_crystal": 1.49, "remark": "", "spin": "", "r_ionic": 1.35},
                              "IX": {"r_crystal": 1.44, "remark": "", "spin": "", "r_ionic": 1.3}}},
                 "Zr": {"4": {"IX": {"r_crystal": 1.03, "remark": "", "spin": "", "r_ionic": 0.89},
                              "VI": {"r_crystal": 0.86, "remark": "R*", "spin": "", "r_ionic": 0.72},
                              "VII": {"r_crystal": 0.92, "remark": "*", "spin": "", "r_ionic": 0.78},
                              "IV": {"r_crystal": 0.73, "remark": "R", "spin": "", "r_ionic": 0.59},
                              "VIII": {"r_crystal": 0.98, "remark": "*", "spin": "", "r_ionic": 0.84},
                              "V": {"r_crystal": 0.8, "remark": "C", "spin": "", "r_ionic": 0.66}},
                        "2": {"VI": {"r_crystal": "", "remark": "R*", "spin": "", "r_ionic": 0.9}}},

                 "Er": {"3": {"VI": {"r_crystal": 1.03, "remark": "R", "spin": "", "r_ionic": 0.89},
                              "VII": {"r_crystal": 1.085, "remark": "", "spin": "", "r_ionic": 0.945},
                              "VIII": {"r_crystal": 1.144, "remark": "R", "spin": "", "r_ionic": 1.004},
                              "IX": {"r_crystal": 1.202, "remark": "R", "spin": "", "r_ionic": 1.062}}},
                 "Ni": {"3": {"": {"r_crystal": 0.74, "remark": "E", "spin": "High Spin", "r_ionic": 0.6},
                              "VI": {"r_crystal": 0.7, "remark": "R*", "spin": "Low Spin", "r_ionic": 0.56}},
                        "2": {"IVSQ": {"r_crystal": 0.63, "remark": "", "spin": "", "r_ionic": 0.49},
                              "VI": {"r_crystal": 0.83, "remark": "R*", "spin": "", "r_ionic": 0.69},
                              "V": {"r_crystal": 0.77, "remark": "E", "spin": "", "r_ionic": 0.63},
                              "IV": {"r_crystal": 0.69, "remark": "", "spin": "", "r_ionic": 0.55}},
                        "4": {"VI": {"r_crystal": 0.62, "remark": "R", "spin": "Low Spin", "r_ionic": 0.48}}},
                 "No": {"2": {"VI": {"r_crystal": 1.24, "remark": "E", "spin": "", "r_ionic": 1.1}}},
                 "Na": {"1": {"IX": {"r_crystal": 1.38, "remark": "C", "spin": "", "r_ionic": 1.24},
                              "VI": {"r_crystal": 1.16, "remark": "", "spin": "", "r_ionic": 1.02},
                              "VII": {"r_crystal": 1.26, "remark": "", "spin": "", "r_ionic": 1.12},
                              "IV": {"r_crystal": 1.13, "remark": "", "spin": "", "r_ionic": 0.99},
                              "VIII": {"r_crystal": 1.32, "remark": "", "spin": "", "r_ionic": 1.18},
                              "XII": {"r_crystal": 1.53, "remark": "", "spin": "", "r_ionic": 1.39},
                              "V": {"r_crystal": 1.14, "remark": "", "spin": "", "r_ionic": 1}}},
                 "Nb": {"2": {"VI": {"r_crystal": "", "remark": "R", "spin": "", "r_ionic": 0.72}}, #dont know, assume similar to Nb3+
                        "3": {"VI": {"r_crystal": 0.86, "remark": "", "spin": "", "r_ionic": 0.72}},
                        "5": {"VI": {"r_crystal": 0.78, "remark": "", "spin": "", "r_ionic": 0.64},
                              "VII": {"r_crystal": 0.83, "remark": "C", "spin": "", "r_ionic": 0.69},
                              "VIII": {"r_crystal": 0.88, "remark": "", "spin": "", "r_ionic": 0.74},
                              "IV": {"r_crystal": 0.62, "remark": "C", "spin": "", "r_ionic": 0.48}},
                        "4": {"VI": {"r_crystal": 0.82, "remark": "RE", "spin": "", "r_ionic": 0.68},
                              "VIII": {"r_crystal": 0.93, "remark": "", "spin": "", "r_ionic": 0.79}}},
                 "Nd": {"3": {"VI": {"r_crystal": 1.123, "remark": "R", "spin": "", "r_ionic": 0.983},
                              "VIII": {"r_crystal": 1.249, "remark": "R*", "spin": "", "r_ionic": 1.109},
                              "XII": {"r_crystal": 1.41, "remark": "E", "spin": "", "r_ionic": 1.27},
                              "IX": {"r_crystal": 1.303, "remark": "R", "spin": "", "r_ionic": 1.163}},
                        "2": {"IX": {"r_crystal": 1.49, "remark": "", "spin": "", "r_ionic": 1.35},
                              "VIII": {"r_crystal": 1.43, "remark": "", "spin": "", "r_ionic": 1.29}}},
                 "Np": {"3": {"VI": {"r_crystal": 1.15, "remark": "R", "spin": "", "r_ionic": 1.01}},
                        "2": {"VI": {"r_crystal": 1.24, "remark": "", "spin": "", "r_ionic": 1.1}},
                        "5": {"VI": {"r_crystal": 0.89, "remark": "", "spin": "", "r_ionic": 0.75}},
                        "4": {"VI": {"r_crystal": 1.01, "remark": "R", "spin": "", "r_ionic": 0.87},
                              "VIII": {"r_crystal": 1.12, "remark": "R", "spin": "", "r_ionic": 0.98}},
                        "7": {"VI": {"r_crystal": 0.85, "remark": "A", "spin": "", "r_ionic": 0.71}},
                        "6": {"VI": {"r_crystal": 0.86, "remark": "R", "spin": "", "r_ionic": 0.72}}},
                 "Fr": {"1": {"VI": {"r_crystal": 1.94, "remark": "A", "spin": "", "r_ionic": 1.8}}},
                 "Fe": {"3": {"": {"r_crystal": 0.785, "remark": "R*", "spin": "High Spin", "r_ionic": 0.645},
                              "VI": {"r_crystal": 0.69, "remark": "R", "spin": "Low Spin", "r_ionic": 0.55},
                              "V": {"r_crystal": 0.72, "remark": "", "spin": "", "r_ionic": 0.58},
                              "VIII": {"r_crystal": 0.92, "remark": "", "spin": "High Spin", "r_ionic": 0.78},
                              "IV": {"r_crystal": 0.63, "remark": "*", "spin": "High Spin", "r_ionic": 0.49}},
                        "2": {"": {"r_crystal": 0.92, "remark": "R*", "spin": "High Spin", "r_ionic": 0.78},
                              "IVSQ": {"r_crystal": 0.78, "remark": "", "spin": "High Spin", "r_ionic": 0.64},
                              "VI": {"r_crystal": 0.75, "remark": "E", "spin": "Low Spin", "r_ionic": 0.61},
                              "VIII": {"r_crystal": 1.06, "remark": "C", "spin": "High Spin", "r_ionic": 0.92},
                              "IV": {"r_crystal": 0.77, "remark": "", "spin": "High Spin", "r_ionic": 0.63}},
                        "4": {"VI": {"r_crystal": 0.725, "remark": "R", "spin": "", "r_ionic": 0.585}},
                        "6": {"IV": {"r_crystal": 0.39, "remark": "R", "spin": "", "r_ionic": 0.25}}},
                 "B": {"3": {"VI": {"r_crystal": 0.41, "remark": "C", "spin": "", "r_ionic": 0.27},
                             "III": {"r_crystal": 0.15, "remark": "*", "spin": "", "r_ionic": 0.01},
                             "IV": {"r_crystal": 0.25, "remark": "*", "spin": "", "r_ionic": 0.11}}},
                 "F": {"-1": {"II": {"r_crystal": 1.145, "remark": "", "spin": "", "r_ionic": 1.285},
                              "VI": {"r_crystal": 1.19, "remark": "", "spin": "", "r_ionic": 1.33},
                              "III": {"r_crystal": 1.16, "remark": "", "spin": "", "r_ionic": 1.3},
                              "IV": {"r_crystal": 1.17, "remark": "", "spin": "", "r_ionic": 1.31}},
                       "7": {"VI": {"r_crystal": 0.22, "remark": "A", "spin": "", "r_ionic": 0.08}}},
                 "Sr": {"2": {"IX": {"r_crystal": 1.45, "remark": "", "spin": "", "r_ionic": 1.31},
                              "VI": {"r_crystal": 1.32, "remark": "", "spin": "", "r_ionic": 1.18},
                              "VII": {"r_crystal": 1.35, "remark": "", "spin": "", "r_ionic": 1.21},
                              "VIII": {"r_crystal": 1.4, "remark": "", "spin": "", "r_ionic": 1.26},
                              "XII": {"r_crystal": 1.58, "remark": "C", "spin": "", "r_ionic": 1.44},
                              "X": {"r_crystal": 1.5, "remark": "C", "spin": "", "r_ionic": 1.36}}},
                 "N": {"3": {"VI": {"r_crystal": 0.3, "remark": "A", "spin": "", "r_ionic": 0.16}},
                       "5": {"VI": {"r_crystal": 0.27, "remark": "A", "spin": "", "r_ionic": 0.13},
                             "III": {"r_crystal": 0.044, "remark": "", "spin": "", "r_ionic": -0.104}},
                       "-3": {"IV": {"r_crystal": 1.32, "remark": "", "spin": "", "r_ionic": 1.46}}},
                 "Si": {"4": {"VI": {"r_crystal": 0.54, "remark": "R*", "spin": "", "r_ionic": 0.4},
                              "IV": {"r_crystal": 0.4, "remark": "*", "spin": "", "r_ionic": 0.26}},
                        "2": {"VI": {"r_crystal": 0.64, "remark": "A", "spin": "", "r_ionic": 0.5}}}, # Si+ is about 0.6, so extrapolate between the two
                 "Sn": {"4": {"VI": {"r_crystal": 0.83, "remark": "R*", "spin": "", "r_ionic": 0.69},
                              "V": {"r_crystal": 0.76, "remark": "C", "spin": "", "r_ionic": 0.62},
                              "VIII": {"r_crystal": 0.95, "remark": "C", "spin": "", "r_ionic": 0.81},
                              "VII": {"r_crystal": 0.89, "remark": "", "spin": "", "r_ionic": 0.75},
                              "IV": {"r_crystal": 0.69, "remark": "R", "spin": "", "r_ionic": 0.55}},
                        "2": {"VI": {"r_crystal": 0.64, "remark": "A", "spin": "", "r_ionic": 1.18}}}, #http://www.wiredchemist.com/chemistry/data/metallic-radii
                 "Sm": {"3": {"VI": {"r_crystal": 1.098, "remark": "R", "spin": "", "r_ionic": 0.958},
                              "VII": {"r_crystal": 1.16, "remark": "E", "spin": "", "r_ionic": 1.02},
                              "VIII": {"r_crystal": 1.219, "remark": "R", "spin": "", "r_ionic": 1.079},
                              "XII": {"r_crystal": 1.38, "remark": "C", "spin": "", "r_ionic": 1.24},
                              "IX": {"r_crystal": 1.272, "remark": "R", "spin": "", "r_ionic": 1.132}},
                        "2": {"IX": {"r_crystal": 1.46, "remark": "", "spin": "", "r_ionic": 1.32},
                              "VII": {"r_crystal": 1.36, "remark": "", "spin": "", "r_ionic": 1.22},
                              "VIII": {"r_crystal": 1.41, "remark": "", "spin": "", "r_ionic": 1.27}}},
                 "V": {"3": {"VI": {"r_crystal": 0.78, "remark": "R*", "spin": "", "r_ionic": 0.64}},
                       "2": {"VI": {"r_crystal": 0.93, "remark": "", "spin": "", "r_ionic": 0.79}},
                       "5": {"VI": {"r_crystal": 0.68, "remark": "", "spin": "", "r_ionic": 0.54},
                             "V": {"r_crystal": 0.6, "remark": "*", "spin": "", "r_ionic": 0.46},
                             "IV": {"r_crystal": 0.495, "remark": "R*", "spin": "", "r_ionic": 0.355}},
                       "4": {"VI": {"r_crystal": 0.72, "remark": "R*", "spin": "", "r_ionic": 0.58},
                             "VIII": {"r_crystal": 0.86, "remark": "E", "spin": "", "r_ionic": 0.72},
                             "V": {"r_crystal": 0.67, "remark": "", "spin": "", "r_ionic": 0.53}}},
                 "Sc": {"3": {"VI": {"r_crystal": 0.885, "remark": "R*", "spin": "", "r_ionic": 0.745},
                              "VIII": {"r_crystal": 1.01, "remark": "R*", "spin": "", "r_ionic": 0.87}},
                        "2": {"VI": {"r_crystal": 0.94, "remark": "R*", "spin": "", "r_ionic": 0.9}}}, #rough estimate from 3+ and 1+ https://www.webelements.com/scandium/atom_sizes.html
                 "Sb": {"3": {"IVPY": {"r_crystal": 0.9, "remark": "", "spin": "", "r_ionic": 0.76},
                              "VI": {"r_crystal": 0.9, "remark": "A", "spin": "", "r_ionic": 0.76},
                              "V": {"r_crystal": 0.94, "remark": "", "spin": "", "r_ionic": 0.8}},
                        "5": {"VI": {"r_crystal": 0.74, "remark": "*", "spin": "", "r_ionic": 0.6}}},
                 "Se": {"6": {"VI": {"r_crystal": 0.56, "remark": "C", "spin": "", "r_ionic": 0.42},
                              "IV": {"r_crystal": 0.42, "remark": "*", "spin": "", "r_ionic": 0.28}},
                        "4": {"VI": {"r_crystal": 0.64, "remark": "A", "spin": "", "r_ionic": 0.5}},
                        "2": {"VI": {"r_crystal": 0.64, "remark": "A", "spin": "", "r_ionic": 0.4}}, # this is an extrapolated value from 6+ and 4+ states
                        "-2": {"VI": {"r_crystal": 1.84, "remark": "P", "spin": "", "r_ionic": 1.98}}},
                 "Co": {"3": {"": {"r_crystal": 0.685, "remark": "R*", "spin": "Low Spin", "r_ionic": 0.545},
                              "VI": {"r_crystal": 0.75, "remark": "", "spin": "High Spin", "r_ionic": 0.61}},
                        "2": {"": {"r_crystal": 0.885, "remark": "R*", "spin": "High Spin", "r_ionic": 0.745},
                              "VI": {"r_crystal": 0.79, "remark": "R", "spin": "Low Spin", "r_ionic": 0.65},
                              "V": {"r_crystal": 0.81, "remark": "C", "spin": "", "r_ionic": 0.67},
                              "VIII": {"r_crystal": 1.04, "remark": "", "spin": "", "r_ionic": 0.9},
                              "IV": {"r_crystal": 0.72, "remark": "", "spin": "High Spin", "r_ionic": 0.58}},
                        "4": {"VI": {"r_crystal": 0.67, "remark": "R", "spin": "High Spin", "r_ionic": 0.53},
                              "IV": {"r_crystal": 0.54, "remark": "", "spin": "", "r_ionic": 0.4}}},
                 "Cm": {"3": {"VI": {"r_crystal": 1.11, "remark": "R", "spin": "", "r_ionic": 0.97}},
                        "4": {"VI": {"r_crystal": 0.99, "remark": "R", "spin": "", "r_ionic": 0.85},
                              "VIII": {"r_crystal": 1.09, "remark": "R", "spin": "", "r_ionic": 0.95}}},
                 "Cl": {"5": {"IIIPY": {"r_crystal": 0.26, "remark": "", "spin": "", "r_ionic": 0.12}},
                        "-1": {"VI": {"r_crystal": 1.67, "remark": "P", "spin": "", "r_ionic": 1.81}},
                        "7": {"VI": {"r_crystal": 0.41, "remark": "A", "spin": "", "r_ionic": 0.27},
                              "IV": {"r_crystal": 0.22, "remark": "*", "spin": "", "r_ionic": 0.08}}},
                 "Ca": {"2": {"IX": {"r_crystal": 1.32, "remark": "", "spin": "", "r_ionic": 1.18},
                              "VI": {"r_crystal": 1.14, "remark": "", "spin": "", "r_ionic": 1},
                              "VII": {"r_crystal": 1.2, "remark": "*", "spin": "", "r_ionic": 1.06},
                              "VIII": {"r_crystal": 1.26, "remark": "*", "spin": "", "r_ionic": 1.12},
                              "XII": {"r_crystal": 1.48, "remark": "C", "spin": "", "r_ionic": 1.34},
                              "X": {"r_crystal": 1.37, "remark": "C", "spin": "", "r_ionic": 1.23}}},
                 "Cf": {"3": {"VI": {"r_crystal": 1.09, "remark": "R", "spin": "", "r_ionic": 0.95}},
                        "4": {"VI": {"r_crystal": 0.961, "remark": "R", "spin": "", "r_ionic": 0.821},
                              "VIII": {"r_crystal": 1.06, "remark": "", "spin": "", "r_ionic": 0.92}}},
                 "Ce": {"3": {"IX": {"r_crystal": 1.336, "remark": "R", "spin": "", "r_ionic": 1.196},
                              "VI": {"r_crystal": 1.15, "remark": "R", "spin": "", "r_ionic": 1.01},
                              "VII": {"r_crystal": 1.21, "remark": "E", "spin": "", "r_ionic": 1.07},
                              "VIII": {"r_crystal": 1.283, "remark": "R", "spin": "", "r_ionic": 1.143},
                              "XII": {"r_crystal": 1.48, "remark": "C", "spin": "", "r_ionic": 1.34},
                              "X": {"r_crystal": 1.39, "remark": "", "spin": "", "r_ionic": 1.25}},
                        "4": {"VI": {"r_crystal": 1.01, "remark": "R", "spin": "", "r_ionic": 0.87},
                              "VIII": {"r_crystal": 1.11, "remark": "R", "spin": "", "r_ionic": 0.97},
                              "XII": {"r_crystal": 1.28, "remark": "", "spin": "", "r_ionic": 1.14},
                              "X": {"r_crystal": 1.21, "remark": "", "spin": "", "r_ionic": 1.07}}},
                 "Cd": {"2": {"VII": {"r_crystal": 1.17, "remark": "C", "spin": "", "r_ionic": 1.03},
                              "VI": {"r_crystal": 1.09, "remark": "", "spin": "", "r_ionic": 0.95},
                              "V": {"r_crystal": 1.01, "remark": "", "spin": "", "r_ionic": 0.87},
                              "IV": {"r_crystal": 0.92, "remark": "", "spin": "", "r_ionic": 0.78},
                              "VIII": {"r_crystal": 1.24, "remark": "C", "spin": "", "r_ionic": 1.1},
                              "XII": {"r_crystal": 1.45, "remark": "", "spin": "", "r_ionic": 1.31}}},
                 "Tm": {"3": {"VI": {"r_crystal": 1.02, "remark": "R", "spin": "", "r_ionic": 0.88},
                              "VIII": {"r_crystal": 1.134, "remark": "R", "spin": "", "r_ionic": 0.994},
                              "IX": {"r_crystal": 1.192, "remark": "R", "spin": "", "r_ionic": 1.052}},
                        "2": {"VI": {"r_crystal": 1.17, "remark": "", "spin": "", "r_ionic": 1.03},
                              "VII": {"r_crystal": 1.23, "remark": "", "spin": "", "r_ionic": 1.09}}},
                 "Cs": {"1": {"IX": {"r_crystal": 1.92, "remark": "", "spin": "", "r_ionic": 1.78},
                              "XI": {"r_crystal": 1.99, "remark": "", "spin": "", "r_ionic": 1.85},
                              "VI": {"r_crystal": 1.81, "remark": "", "spin": "", "r_ionic": 1.67},
                              "VIII": {"r_crystal": 1.88, "remark": "", "spin": "", "r_ionic": 1.74},
                              "XII": {"r_crystal": 2.02, "remark": "", "spin": "", "r_ionic": 1.88},
                              "X": {"r_crystal": 1.95, "remark": "", "spin": "", "r_ionic": 1.81}}},
                 "Cr": {"3": {"VI": {"r_crystal": 0.755, "remark": "R*", "spin": "", "r_ionic": 0.615}},
                        "2": {"": {"r_crystal": 0.94, "remark": "R*", "spin": "High Spin", "r_ionic": 0.8},
                              "VI": {"r_crystal": 0.87, "remark": "E", "spin": "Low Spin", "r_ionic": 0.73}},
                        "5": {"VI": {"r_crystal": 0.63, "remark": "ER", "spin": "", "r_ionic": 0.49},
                              "VIII": {"r_crystal": 0.71, "remark": "", "spin": "", "r_ionic": 0.57},
                              "IV": {"r_crystal": 0.485, "remark": "R", "spin": "", "r_ionic": 0.345}},
                        "4": {"VI": {"r_crystal": 0.69, "remark": "R", "spin": "", "r_ionic": 0.55},
                              "IV": {"r_crystal": 0.55, "remark": "", "spin": "", "r_ionic": 0.41}},
                        "6": {"VI": {"r_crystal": 0.58, "remark": "C", "spin": "", "r_ionic": 0.44},
                              "IV": {"r_crystal": 0.4, "remark": "", "spin": "", "r_ionic": 0.26}}},
                 "Cu": {"1": {"II": {"r_crystal": 0.6, "remark": "", "spin": "", "r_ionic": 0.46},
                              "VI": {"r_crystal": 0.91, "remark": "E", "spin": "", "r_ionic": 0.77},
                              "IV": {"r_crystal": 0.74, "remark": "E", "spin": "", "r_ionic": 0.6}},
                        "3": {"VI": {"r_crystal": 0.68, "remark": "", "spin": "Low Spin", "r_ionic": 0.54}},
                        "2": {"IVSQ": {"r_crystal": 0.71, "remark": "*", "spin": "", "r_ionic": 0.57},
                              "VI": {"r_crystal": 0.87, "remark": "", "spin": "", "r_ionic": 0.73},
                              "V": {"r_crystal": 0.79, "remark": "*", "spin": "", "r_ionic": 0.65},
                              "IV": {"r_crystal": 0.71, "remark": "", "spin": "", "r_ionic": 0.57}}},
                 "La": {"3": {"IX": {"r_crystal": 1.356, "remark": "R", "spin": "", "r_ionic": 1.216},
                              "VI": {"r_crystal": 1.172, "remark": "R", "spin": "", "r_ionic": 1.032},
                              "VII": {"r_crystal": 1.24, "remark": "", "spin": "", "r_ionic": 1.1},
                              "VIII": {"r_crystal": 1.3, "remark": "R", "spin": "", "r_ionic": 1.16},
                              "XII": {"r_crystal": 1.5, "remark": "C", "spin": "", "r_ionic": 1.36},
                              "X": {"r_crystal": 1.41, "remark": "", "spin": "", "r_ionic": 1.27}}},
                 "Li": {"1": {"VI": {"r_crystal": 0.9, "remark": "*", "spin": "", "r_ionic": 0.76},
                              "VIII": {"r_crystal": 1.06, "remark": "C", "spin": "", "r_ionic": 0.92},
                              "IV": {"r_crystal": 0.73, "remark": "*", "spin": "", "r_ionic": 0.59}}},
                 "Tl": {"1": {"VI": {"r_crystal": 1.64, "remark": "R", "spin": "", "r_ionic": 1.5},
                              "VIII": {"r_crystal": 1.73, "remark": "R", "spin": "", "r_ionic": 1.59},
                              "XII": {"r_crystal": 1.84, "remark": "RE", "spin": "", "r_ionic": 1.7}},
                        "3": {"VI": {"r_crystal": 1.025, "remark": "R", "spin": "", "r_ionic": 0.885},
                              "VIII": {"r_crystal": 1.12, "remark": "C", "spin": "", "r_ionic": 0.98},
                              "IV": {"r_crystal": 0.89, "remark": "", "spin": "", "r_ionic": 0.75}}},
                 "Lu": {"3": {"VI": {"r_crystal": 1.001, "remark": "R", "spin": "", "r_ionic": 0.861},
                              "VIII": {"r_crystal": 1.117, "remark": "R", "spin": "", "r_ionic": 0.977},
                              "IX": {"r_crystal": 1.172, "remark": "R", "spin": "", "r_ionic": 1.032}}},
                 "Th": {"4": {"IX": {"r_crystal": 1.23, "remark": "*", "spin": "", "r_ionic": 1.09},
                              "XI": {"r_crystal": 1.32, "remark": "C", "spin": "", "r_ionic": 1.18},
                              "VI": {"r_crystal": 1.08, "remark": "C", "spin": "", "r_ionic": 0.94},
                              "VIII": {"r_crystal": 1.19, "remark": "RC", "spin": "", "r_ionic": 1.05},
                              "XII": {"r_crystal": 1.35, "remark": "C", "spin": "", "r_ionic": 1.21},
                              "X": {"r_crystal": 1.27, "remark": "E", "spin": "", "r_ionic": 1.13}}},
                 "Ti": {"3": {"VI": {"r_crystal": 0.81, "remark": "R*", "spin": "", "r_ionic": 0.67}},
                        "2": {"VI": {"r_crystal": 1, "remark": "E", "spin": "", "r_ionic": 0.86}},
                        "4": {"VI": {"r_crystal": 0.745, "remark": "R*", "spin": "", "r_ionic": 0.605},
                              "V": {"r_crystal": 0.65, "remark": "C", "spin": "", "r_ionic": 0.51},
                              "VIII": {"r_crystal": 0.88, "remark": "C", "spin": "", "r_ionic": 0.74},
                              "IV": {"r_crystal": 0.56, "remark": "C", "spin": "", "r_ionic": 0.42}}},
                 "Te": {"6": {"VI": {"r_crystal": 0.7, "remark": "*", "spin": "", "r_ionic": 0.56},
                              "IV": {"r_crystal": 0.57, "remark": "C", "spin": "", "r_ionic": 0.43}},
                        "4": {"VI": {"r_crystal": 1.11, "remark": "", "spin": "", "r_ionic": 0.97},
                              "III": {"r_crystal": 0.66, "remark": "", "spin": "", "r_ionic": 0.52},
                              "IV": {"r_crystal": 0.8, "remark": "", "spin": "", "r_ionic": 0.66}},
                        "2": {"VI": {"r_crystal": 0.64, "remark": "A", "spin": "", "r_ionic": 1.4}},
                        # this is an extrapolated value from 6+ and 4+ states
                        "-2": {"VI": {"r_crystal": 2.07, "remark": "P", "spin": "", "r_ionic": 2.21}}},
                 "Tb": {"3": {"VI": {"r_crystal": 1.063, "remark": "R", "spin": "", "r_ionic": 0.923},
                              "VII": {"r_crystal": 1.12, "remark": "E", "spin": "", "r_ionic": 0.98},
                              "VIII": {"r_crystal": 1.18, "remark": "R", "spin": "", "r_ionic": 1.04},
                              "IX": {"r_crystal": 1.235, "remark": "R", "spin": "", "r_ionic": 1.095}},
                        "4": {"VI": {"r_crystal": 0.9, "remark": "R", "spin": "", "r_ionic": 0.76},
                              "VIII": {"r_crystal": 1.02, "remark": "", "spin": "", "r_ionic": 0.88}}},
                 "Tc": {"2": {"VI": {"r_crystal": "", "remark": "R*", "spin": "", "r_ionic": 0.8}}, #extrapolate from 5+ and 4+ state
                        "5": {"VI": {"r_crystal": 0.74, "remark": "ER", "spin": "", "r_ionic": 0.6}},
                        "4": {"VI": {"r_crystal": 0.785, "remark": "RM", "spin": "", "r_ionic": 0.645}},
                        "7": {"VI": {"r_crystal": 0.7, "remark": "A", "spin": "", "r_ionic": 0.56},
                              "IV": {"r_crystal": 0.51, "remark": "", "spin": "", "r_ionic": 0.37}}},
                 "Ta": {"2": {"VI": {"r_crystal": "", "remark": "R", "spin": "", "r_ionic": 0.88}}, #extrapolate from III and IV
                        "3": {"VI": {"r_crystal": 0.86, "remark": "E", "spin": "", "r_ionic": 0.72}},
                        "5": {"VI": {"r_crystal": 0.78, "remark": "", "spin": "", "r_ionic": 0.64},
                              "VII": {"r_crystal": 0.83, "remark": "", "spin": "", "r_ionic": 0.69},
                              "VIII": {"r_crystal": 0.88, "remark": "", "spin": "", "r_ionic": 0.74}},
                        "4": {"VI": {"r_crystal": 0.82, "remark": "E", "spin": "", "r_ionic": 0.68}}},
                 "Yb": {"3": {"VI": {"r_crystal": 1.008, "remark": "R*", "spin": "", "r_ionic": 0.868},
                              "VII": {"r_crystal": 1.065, "remark": "E", "spin": "", "r_ionic": 0.925},
                              "VIII": {"r_crystal": 1.125, "remark": "R", "spin": "", "r_ionic": 0.985},
                              "IX": {"r_crystal": 1.182, "remark": "R", "spin": "", "r_ionic": 1.042}},
                        "2": {"VI": {"r_crystal": 1.16, "remark": "", "spin": "", "r_ionic": 1.02},
                              "VII": {"r_crystal": 1.22, "remark": "E", "spin": "", "r_ionic": 1.08},
                              "VIII": {"r_crystal": 1.28, "remark": "", "spin": "", "r_ionic": 1.14}}},
                 "Dy": {"3": {"VI": {"r_crystal": 1.052, "remark": "R", "spin": "", "r_ionic": 0.912},
                              "VII": {"r_crystal": 1.11, "remark": "", "spin": "", "r_ionic": 0.97},
                              "VIII": {"r_crystal": 1.167, "remark": "R", "spin": "", "r_ionic": 1.027},
                              "IX": {"r_crystal": 1.223, "remark": "R", "spin": "", "r_ionic": 1.083}},
                        "2": {"VI": {"r_crystal": 1.21, "remark": "", "spin": "", "r_ionic": 1.07},
                              "VII": {"r_crystal": 1.27, "remark": "", "spin": "", "r_ionic": 1.13},
                              "VIII": {"r_crystal": 1.33, "remark": "", "spin": "", "r_ionic": 1.19}}},
                 "I": {"5": {"VI": {"r_crystal": 1.09, "remark": "", "spin": "", "r_ionic": 0.95},
                             "IIIPY": {"r_crystal": 0.58, "remark": "*", "spin": "", "r_ionic": 0.44}},
                       "-1": {"VI": {"r_crystal": 2.06, "remark": "A", "spin": "", "r_ionic": 2.2}},
                       "7": {"VI": {"r_crystal": 0.67, "remark": "", "spin": "", "r_ionic": 0.53},
                             "IV": {"r_crystal": 0.56, "remark": "", "spin": "", "r_ionic": 0.42}}},
                 "U": {"3": {"VI": {"r_crystal": 1.165, "remark": "R", "spin": "", "r_ionic": 1.025}},
                       "5": {"VI": {"r_crystal": 0.9, "remark": "", "spin": "", "r_ionic": 0.76},
                             "VII": {"r_crystal": 0.98, "remark": "E", "spin": "", "r_ionic": 0.84}},
                       "4": {"VI": {"r_crystal": 1.03, "remark": "", "spin": "", "r_ionic": 0.89},
                             "VII": {"r_crystal": 1.09, "remark": "E", "spin": "", "r_ionic": 0.95},
                             "VIII": {"r_crystal": 1.14, "remark": "R*", "spin": "", "r_ionic": 1},
                             "XII": {"r_crystal": 1.31, "remark": "E", "spin": "", "r_ionic": 1.17},
                             "IX": {"r_crystal": 1.19, "remark": "", "spin": "", "r_ionic": 1.05}},
                       "6": {"II": {"r_crystal": 0.59, "remark": "", "spin": "", "r_ionic": 0.45},
                             "VI": {"r_crystal": 0.87, "remark": "*", "spin": "", "r_ionic": 0.73},
                             "VII": {"r_crystal": 0.95, "remark": "E", "spin": "", "r_ionic": 0.81},
                             "VIII": {"r_crystal": 1, "remark": "", "spin": "", "r_ionic": 0.86},
                             "IV": {"r_crystal": 0.66, "remark": "", "spin": "", "r_ionic": 0.52}}},
                 "Y": {"2": {"VI": {"r_crystal": 1.04, "remark": "R*", "spin": "", "r_ionic": 1.065}},
                        "3": {"VI": {"r_crystal": 1.04, "remark": "R*", "spin": "", "r_ionic": 0.9},
                             "VII": {"r_crystal": 1.1, "remark": "", "spin": "", "r_ionic": 0.96},
                             "VIII": {"r_crystal": 1.159, "remark": "R*", "spin": "", "r_ionic": 1.019},
                             "IX": {"r_crystal": 1.215, "remark": "R", "spin": "", "r_ionic": 1.075}}},
                 "Ac": {"3": {"VI": {"r_crystal": 1.26, "remark": "R", "spin": "", "r_ionic": 1.12}}},
                 "Ag": {"1": {"VII": {"r_crystal": 1.36, "remark": "", "spin": "", "r_ionic": 1.22},
                              "IVSQ": {"r_crystal": 1.16, "remark": "", "spin": "", "r_ionic": 1.02},
                              "V": {"r_crystal": 1.23, "remark": "C", "spin": "", "r_ionic": 1.09},
                              "IV": {"r_crystal": 1.14, "remark": "C", "spin": "", "r_ionic": 1},
                              "II": {"r_crystal": 0.81, "remark": "", "spin": "", "r_ionic": 0.67},
                              "VIII": {"r_crystal": 1.42, "remark": "", "spin": "", "r_ionic": 1.28},
                              "VI": {"r_crystal": 1.29, "remark": "C", "spin": "", "r_ionic": 1.15}},
                        "3": {"IVSQ": {"r_crystal": 0.81, "remark": "", "spin": "", "r_ionic": 0.67},
                              "VI": {"r_crystal": 0.89, "remark": "R", "spin": "", "r_ionic": 0.75}},
                        "2": {"IVSQ": {"r_crystal": 0.93, "remark": "", "spin": "", "r_ionic": 0.79},
                              "VI": {"r_crystal": 1.08, "remark": "", "spin": "", "r_ionic": 0.94}}},
                 "Ir": {"2": {"VI": {"r_crystal": "", "remark": "E", "spin": "", "r_ionic": 0.7}},
                        "3": {"VI": {"r_crystal": 0.82, "remark": "E", "spin": "", "r_ionic": 0.68}},
                        "5": {"VI": {"r_crystal": 0.71, "remark": "EM", "spin": "", "r_ionic": 0.57}},
                        "4": {"VI": {"r_crystal": 0.765, "remark": "R", "spin": "", "r_ionic": 0.625}}},
                 "Am": {"3": {"VI": {"r_crystal": 1.115, "remark": "R", "spin": "", "r_ionic": 0.975},
                              "VIII": {"r_crystal": 1.23, "remark": "", "spin": "", "r_ionic": 1.09}},
                        "2": {"IX": {"r_crystal": 1.45, "remark": "", "spin": "", "r_ionic": 1.31},
                              "VII": {"r_crystal": 1.35, "remark": "", "spin": "", "r_ionic": 1.21},
                              "VIII": {"r_crystal": 1.4, "remark": "", "spin": "", "r_ionic": 1.26}},
                        "4": {"VI": {"r_crystal": 0.99, "remark": "R", "spin": "", "r_ionic": 0.85},
                              "VIII": {"r_crystal": 1.09, "remark": "", "spin": "", "r_ionic": 0.95}}},
                 "Al": {"3": {"VI": {"r_crystal": 0.675, "remark": "R*", "spin": "", "r_ionic": 0.535},
                              "V": {"r_crystal": 0.62, "remark": "", "spin": "", "r_ionic": 0.48},
                              "IV": {"r_crystal": 0.53, "remark": "*", "spin": "", "r_ionic": 0.39}}},
                 "As": {"3": {"VI": {"r_crystal": 0.72, "remark": "A", "spin": "", "r_ionic": 0.58}},
                        "5": {"VI": {"r_crystal": 0.6, "remark": "C*", "spin": "", "r_ionic": 0.46},
                              "IV": {"r_crystal": 0.475, "remark": "R*", "spin": "", "r_ionic": 0.335}},
                         "2": {"VI": {"r_crystal": 0.64, "remark": "A", "spin": "", "r_ionic": 0.6}}},
                         # this is an extrapolated value

                 "Au": {"1": {"VI": {"r_crystal": 1.51, "remark": "A", "spin": "", "r_ionic": 1.37}},
                        "3": {"IVSQ": {"r_crystal": 0.82, "remark": "", "spin": "", "r_ionic": 0.68},
                              "VI": {"r_crystal": 0.99, "remark": "A", "spin": "", "r_ionic": 0.85}},
                        "2": {"VI": {"r_crystal": "", "remark": "E", "spin": "", "r_ionic": 1.25}},
                        "5": {"VI": {"r_crystal": 0.71, "remark": "", "spin": "", "r_ionic": 0.57}}},
                 "At": {"7": {"VI": {"r_crystal": 0.76, "remark": "A", "spin": "", "r_ionic": 0.62}}},
                 "In": {"1": {"VI": {"r_crystal": 0.94, "remark": "R*", "spin": "", "r_ionic": 1.04}},
                        "2": {"VI": {"r_crystal": 0.94, "remark": "R*", "spin": "", "r_ionic": 0.9}},
                        "3": {"VI": {"r_crystal": 0.94, "remark": "R*", "spin": "", "r_ionic": 0.8},
                              "VIII": {"r_crystal": 1.06, "remark": "RC", "spin": "", "r_ionic": 0.92},
                              "IV": {"r_crystal": 0.76, "remark": "", "spin": "", "r_ionic": 0.62}}},
                 "Mo": {"2": {"VI": {"r_crystal": "", "remark": "R", "spin": "", "r_ionic": 0.85}}, #extrapolate from 1+ and 3+ https://www.webelements.com/molybdenum/atom_sizes.html
                        "3": {"VI": {"r_crystal": 0.83, "remark": "E", "spin": "", "r_ionic": 0.69}},
                        "5": {"VI": {"r_crystal": 0.75, "remark": "R", "spin": "", "r_ionic": 0.61},
                              "IV": {"r_crystal": 0.6, "remark": "R", "spin": "", "r_ionic": 0.46}},
                        "4": {"VI": {"r_crystal": 0.79, "remark": "RM", "spin": "", "r_ionic": 0.65}},
                        "6": {"VI": {"r_crystal": 0.73, "remark": "R*", "spin": "", "r_ionic": 0.59},
                              "V": {"r_crystal": 0.64, "remark": "", "spin": "", "r_ionic": 0.5},
                              "VII": {"r_crystal": 0.87, "remark": "", "spin": "", "r_ionic": 0.73},
                              "IV": {"r_crystal": 0.55, "remark": "R*", "spin": "", "r_ionic": 0.41}}}}
